### ISSUE TITLE
Running into an error with child routes

### ISSUE THREAD

**Issue by davegonzalez** [4Catalyzer/found#101]
Hi there! I was checking out Found for use on a project that I'm about to work on. While playing with it, I tried doing this:

```js
const routeConfig = [
  {
    path: 'admin',
    Component: App,
    children: [
      {
        path: 'promotions',
        Component: () => <div>promos</div>,
        children: [
          {
            path: ':id/edit',
            Component: () => <div>here</div>,
          }
        ]
      },
    ]
  }
]
```
The route changes, but the component does not. If I change the nested `:id/edit` path to `path: 'promotions/:id/edit'`

I get the following error:
```
invariant.js?4599:44 Uncaught (in promise) Error: Objects are not valid as a React child (found: object with keys {status, data}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
```

However, it does work if I do:

```js
const routeConfig = [
  {
    path: 'admin',
    Component: App,
    children: [
      {
        path: 'promotions',
        Component: () => <div>promos</div>
      },
      {
        path: 'promotions/:id/edit',
        Component: () => <div>here</div>,
      }
    ]
  }
]
```

After looking through the examples, I was under the impression that a child route could have children i.e., https://github.com/4Catalyzer/found#basic-usage

Am I using this incorrectly? Or is it because I'm setting the root path to `admin` instead of `/`?

**Comment by taion** [comment]
You need to render `props.children` from the component for the route with the `promotions` path in the earlier example if you want to see that child.

**Comment by davegonzalez** [comment]
Ah of course! Thanks!
