### ISSUE TITLE
found w/ knex (postgres) - knex client.driver.Client is not a constructor

### ISSUE THREAD

**Issue by Falieson** [4Catalyzer/found#103]
I started this issue a week ago https://github.com/tgriesser/knex/issues/2121 thinking it was an issue with Knex but I've experimented doing the same code with react-router-4 and its working perfectly.

Found: https://github.com/Falieson/ultimate-react-2017/commit/f9d9a31980955844862f7b584dfdaa3a34d571c9#commitcomment-22539375

ReactRouter: https://github.com/Falieson/simple-react-express/commit/6771400e58146e1ead53372c08ac5db7aa474db4

**Comment by Falieson** [comment]
My next steps on this issue are:
1) restart the ultimate-react-2017 repo off that simple-react-express (w/ RR4) repo
2) pull out RR4 and implement found 

and maybe the minor difference in webpack or some other config is whats causing the issue and nothing to do with your package

**Comment by taion** [comment]
I'd suggest adding some instrumentation there to see what `Client` is. Seems odd that you're trying to access Postgres directly from client code, though – like, that only makes sense on the server anyway, since clients almost never directly have access to your database.
