### ISSUE TITLE
Link always use 'PUSH' action despite `action` in location descriptor

### ISSUE THREAD

**Issue by gnhuy91** [4Catalyzer/found#111]
Hi, below `Link` always use `PUSH` regardless of `action`. Is this behavior correct?

```jsx
<Link
      to={{
        action: 'REPLACE',
        pathname: '/home',
      }}
    >
```

**Comment by taion** [comment]
This is intentional. If you're replacing, you really don't have link-like semantics, so it'd probably be best to build a custom button.
