### ISSUE TITLE
Route component prerender not receiving correct props upon programmatic navigation

### ISSUE THREAD

**Issue by hamza** [4Catalyzer/found#121]
I'm using the following scheme for checking for a logged-in user using Found (along with Relay Modern) -

```jsx
  <Route
    path="/"
    Component={App}
    prerender={ ({ props, match }) => {
      const login_path = match.location.pathname == "/login";
      const logged_in = props && !!props.viewer;

      if (login_path && logged_in) {
        throw new RedirectException("/");
      } else if (!login_path && !logged_in) {
        throw new RedirectException("/login");
      }
    }}
    query={graphql`
      query routes_Query {
        viewer {
          ...App_viewer
        }
      }
    `}
  >
```

This works fine for the most part, except in my login mutation, when I want to programmatically navigate to the root route upon login success (excerpt from mutation) -

```js
onCompleted: (response) => {
  if (response.login.success) {
    router.replace("/");
  } else {
    console.log("Auth failed");
  }
},
```

**Issue**
When I perform the navigation using this technique, my `prerender` handler doesn't receive the new props (specifically in my case, `viewer` remains `null`). However, if I do a hard page refresh at that point, things function as expected.

Does this sound like a bug? Or am I just doing something fishy

**Comment by taion** [comment]
Is it `null` or `undefined`? This looks like login code, so it's possible you have some sort of race condition such that you actually _are_ getting back `null` for `viewer`.

**Comment by hamza** [comment]
A breakpoint reveals that there are two trips through `prerender`, and each time `props.viewer` is `null`.

![image](https://user-images.githubusercontent.com/4432375/29953365-64504b90-8e84-11e7-85c8-eed66b7c810c.png)

I've thought about a race condition, but ruled out one at least on the server side. A breakpoint in the resolver for `viewer` reveals that it is in fact being returned by the server.

**Comment by taion** [comment]
What do you see on your network layer?

**Comment by hamza** [comment]
Attached screenshot
![image](https://user-images.githubusercontent.com/4432375/29982229-c059967c-8f05-11e7-9293-561c893f8018.png)

**Comment by hamza** [comment]
I can provide source code if that would be more helpful for reproducing the issue. This is seeming more like a bug and less like user error on my part. 🤔 💭

**Comment by taion** [comment]
If you have some sort of example, it would be really helpful. Also if you could re-open this issue against Found Relay because I keep forgetting it's here.

Otherwise it might be a bit until I have a chance to look at this.

**Comment by patrick-samy** [comment]
I have exactly a similar issue: the route render method handling authentication is called twice and I can't figure out why.

Did you open an issue within found-relay? I can't find it.

**Comment by taion** [comment]
`render` generally will get called twice on anything async – first to try to render a loading indicator if any, next to render the actual component. That's why the examples show checking e.g. `props` in `render`.

**Comment by patrick-samy** [comment]
@taion I see thanks, it was actually an error in Auth0 sample code.

However, I'm having trouble structuring the routes for my application with authentication. What happens is that the query on my main component is fetched before the authentication is done and the API token is available in the local storage.

**Comment by taion** [comment]
I'd recommend handling authN separately from Relay. The way we have it set up is that our routes throw an `HttpError(401)` if there's no auth token. Then our global render handler renders the login page on that error. When the user does log in from that page, then we create a new Relay environment and go from there.

**Comment by patrick-samy** [comment]
Makes sense. The global render handler is the one from your top-level route?

That's where I was heading, right now the "/callback" endpoint handle authentication. I'll move the query to a subroute:
`
<Route Component={App} path="/" query={*viewer*} />
    <Route path="/callback" render={(props) => { handleAuthentication(props); return <LoadingPage />; }} />
</Route>
`

**Comment by taion** [comment]
The thing you make with `createRender` that you pass into the router.

**Comment by patrick-samy** [comment]
Ah, I actually can't use this method as some parts of my application are public.

The best alternative is probably to extend Route and have it check for the auth token, right?

**Comment by taion** [comment]
No, I mean, you do `throw new HttpError(401)` on unauth-ed users only for those routes that require auth. For the rest, you don't. So something like:

```js
<Route
  path="/private"
  render={({ Component, props }) => {
    if (!authorized) {
      throw new HttpError(401);
    }

    return <Component {...props} />;
  }}
/>
<Route
  path="/public"
/>
```

**Comment by taion** [comment]
Alternatively, you can extend `Resolver`, and do something like:

```js
class AuthResolver extends Resolver {
  resolveElements(match) {
    if (!authenticated && match.routes.some(route => route.private)) {
      throw new HttpError(401);
    }

    return super.resolveElements(match);
  }
}
```

**Comment by taion** [comment]
Closing this as we haven't been able to repro the original issue. Also `prerender` is gone for the Relay Modern integration anyway.
