### ISSUE TITLE
Nested `<Route />` being rendered despite parent `<Route />` rendering `null`

### ISSUE THREAD

**Issue by barberdt** [4Catalyzer/found#125]
Hey all. Love the library. Great work.

Having an issue with a complex usage of the Redux-connected `createConnectedRouter` (although I sense my issue is agnostic of the fact that I'm using that as opposed to the "basic" usage).

**My implementation:**
```javascript
function App({ children }) {
  return (
    <div>
      <h1>The App</h1>
      {children}
    </div>
  )
}

function NestedComponent() {
  return <div>The nested component</div>
}

function getData() {
  return promiseReturningFunction().then((someValue) => { someValue })
}

const routeConfig = makeRouteConfig(
  <Route
    path='/'
    Component={App}
    getData={getData}
    render={({ Component, data, props }) => {
      if (!data) {
        return null
      }

      return <Component {...props} />
    }}
  >
    <Route path='/nested' Component={NestedComponent} />
  </Route>
)

const createStoreWithEnhancers = composeEnhancers(
  createHistoryEnhancer({
    protocol: new BrowserProtocol(),
    middlewares: [queryMiddleware],
  }),
  createMatchEnhancer(new Matcher(routeConfig)),
)(createStore)

const reducer = combineReducers({
  found: foundReducer,
})

const store = createStoreWithEnhancers(reducer)
const ConnectedRouter = createConnectedRouter({
  render: createRender({}),
})

ReactDOM.render(
  <Provider store={store}>
    <ConnectedRouter resolver={resolver} />
  </Provider>
)
```

With the code above, I am noticing that on the initial render pass, although the `render` for the top-level `<Route />` is returning `null` (as a result of `getData`), the child `<Route />`'s component (`NestedComponent`) is still getting rendered for a brief moment (without the wrapping `App` component being rendered). Note that the render lifecycle of `App` isn't even being invoked. The `NestedComponent` is rendering completely outside of that context. In the second pass that occurs after `getData` is resolved, both components render as expected (with `NestedComponent` being rendered as a child of `App`).

When tracing the unexpected render of `NestedComponent` it looks like it's simply coming from the `resolveMatch` of the `BasicRouter`.

My expectation would be that child `<Route />`s and their `Component`s do not render if their parent `<Route />`'s `render` is returning `null`. Am I perhaps thinking about this the wrong way?

Happy to provide more debugging information if necessary.

**Edit**
For some added clarification, the visual output is as follows.
1. The page simply reads "The nested component" for the first pass (unexpected).
2. After `getData` is resolved, the page reads (as expected) "The App" followed by "The nested component"

**Comment by taion** [comment]
That's an unfortunate consequence of how routes that don't have a component work by rendering `null`.

For a quick workaround, you could just render a:

```js
function Dummy() {
  return null;
}
```

Longer term, well... `undefined` and `null` are already taken. It might make sense to use `false` to mean "render nothing for this route and its children", if you think using `<Dummy>` above is too messy.

**Comment by barberdt** [comment]
@taion thanks for the reply! The `<Dummy />` solution works great. I guess it would be nice at some point for the library to have a built-in and documented way of saying (in the context of a `<Route />`) "Don't render my component or my child routes and their components", but this totally fine for now.

**Comment by taion** [comment]
Makes sense. If you don't mind, I'd like to leave this open until we add that, then.
