### ISSUE TITLE
wrong version of path-to-regexp bundled - solutions?

### ISSUE THREAD

**Issue by ling1726** [4Catalyzer/found#126]
Hi,

We're using express with found and found-relay. Currently we get a message concerning an outdated path-to-regexp lib. The root cause of this issue is that express uses version 0.1.7 while found uses version 1.7.

> Warning: Incorrect version of path-to-regexp imported. If this is running from a client bundle, check your bundler settings.

Our webpack seems to bundle the 0.1.7 EVERY TIME. Has somebody encountered this issue already and has a solution to it? 

We have already tried to explicitly add path-to-regexp@1.7 as a dependency to the project, but this fix does not seem to work 100% of the time

thx

**Comment by taion** [comment]
It's possible you have DedupePlugin running too aggressively. Also check that your module tree looks right – you may just want to nuke `node_modules` and your lockfile and try again.

I can't really speak to how to make webpack do the right thing in your case specifically beyond the suggestions above.

**Comment by Razinsky** [comment]
I have the same issue here! I cannot make a simple regex path to work. I do the exact same thing as in the doc `/path/:(\d+)id` and it does not seem to be recognized by found at all ... I guess it's because of the bundled path-to-regexp version. @ling1726 any solution on your end?

**Comment by taion** [comment]
Try explicitly installing path-to-regexp@^1 as a top-level dependency. That should make webpack do the right thing.

**Comment by Razinsky** [comment]
Yeah I did set ^2.0.0 as an explicit dependency... I don't know if the issue is related to that because there's no error. The route I set is just not recognized. Here's my definition:

```
<Route
  path="/track/:(\d+)id"
  Component={TrackPage}
  query={TrackPageQuery}
  prepareVariables={(params) => ({ id: params.id })}
/>
```

Thanks.

**Comment by taion** [comment]
You need to do `\\d` instead of `\d` to escape the `\`.

**Comment by Razinsky** [comment]
The `\\d` doesn't help...

**Comment by taion** [comment]
Oh, and it should be `:id(\\d+)`, like in https://github.com/4Catalyzer/found/blob/master/test/Matcher.test.js#L125

Just follow the path-to-regexp docs.

**Comment by Razinsky** [comment]
Ok! Now we're talking. I guess it may be a good idea to update the doc consequently.

Thanks @taion !

**Comment by taion** [comment]
Oh, oops.
