### ISSUE TITLE
Shared redux store with immutable-js

### ISSUE THREAD

**Issue by NSLS** [4Catalyzer/found#129]
Hi! I have recently decided to build a new project and try found instead of RR3, but in my previous project I've always used immutable stores created with redux-immutable.

For a non-immutable.js user it means, that instead of the normal combineReducers, the store is created with a combineReducers from redux-immutable, which creates a Map instead of a normal JS object.

Meaning, that if I would try to use a normal shared-store configuration, it would fail due to inability to access data from an immutable store.

Therefore, my question is - is it possible to make a support for immutable-js users?

It would be really great if you could implement it or at least give me some guidance so I could implement in myself.

Thanks.

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found/blob/v0.3.4/src/createConnectedRouter.js#L15 and https://github.com/4Catalyzer/found/blob/v0.3.4/src/createWithRouter.js#L10 (the latter is used in `createConnectedLink`).

So assuming that you were okay with Found itself using objects, you can in both cases just use a `getFound` that calls `store.get('found')` or whatever else you need.

**Comment by taion** [comment]
Does that work for you?

**Comment by NSLS** [comment]
Hi. Sadly, I didn't have time to check yet, but your proposal should work, so I'm closing this for now and will reopen if I face some problems.

Thanks!

**Comment by lukehedger** [comment]
For anyone else landing here, the solution is:

```
createConnectedRouter({
  getFound: store => store.get('found'),
  ...options,
})
```

**Comment by taion** [comment]
Yup! Note that you'll also need to do the same for `<Link>` and for `withRouter` as well (via `createConnectedLink` and `createWithRouter`), if you use those.

(... probably you're using `<Link>`. I hope. It's a good component.)

**Comment by hollandThomas** [comment]
Hey, I want to do the exact same thing and followed [this](https://github.com/4Catalyzer/found#createconnectedrouter) and the tips in this thread. 

My store looks like this:

```
import { createStore, compose } from 'redux';
import BrowserProtocol from 'farce/lib/BrowserProtocol';
import createHistoryEnhancer from 'farce/lib/createHistoryEnhancer';
import queryMiddleware from 'farce/lib/queryMiddleware';
import createMatchEnhancer from 'found/lib/createMatchEnhancer';
import Matcher from 'found/lib/Matcher';

import rootReducer from './reducers/index';
import routeConfig from '../routes';

// eslint-disable-next-line
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(
  rootReducer,
  composeEnhancers(
    createHistoryEnhancer({
      protocol: new BrowserProtocol(),
      middlewares: [queryMiddleware],
    }),
    createMatchEnhancer(new Matcher(routeConfig)),
  ),
);

export default store;
```

Router:

```
import createConnectedRouter from 'found/lib/createConnectedRouter';
import createRender from 'found/lib/createRender';

const Router = createConnectedRouter({
  render: createRender({}),
});

export default Router;
```

I call `Store.dispatch(Actions.init());` before I pass the Store to the redux Provider.

Also I do not really know what u mean by 

> Note that you'll also need to do the same for <Link> and for withRouter as well (via createConnectedLink and createWithRouter), if you use those.

Do I have to specify a Link like this and use it instead of the provided Link component?

```
import createConnectedLink from 'found/lib/createConnectedLink';

const Link = createConnectedLink({
  getFound: store => store.get('found'),
});

export default Link;
```

No matter what I do, these are the Errors I get:
<img width="810" alt="bildschirmfoto 2017-10-24 um 13 04 52" src="https://user-images.githubusercontent.com/20690465/31939959-aa708bc8-b8bc-11e7-9992-92f99708547e.png">

**Comment by NSLS** [comment]
The reason for this error is most probably because you have forgotten to specify 
`getFound: state => state.get('found')` when calling the createConnectedRouter function.

> Do I have to specify a Link like this and use it instead of the provided Link component?

Yes, exactly, and also do the same with `withRouter`, if you need it

**Comment by lukehedger** [comment]
@hollandThomas - just need to change your `Router.js` slightly:
```
import { createConnectedRouter, createRender } from 'found' // <= can also group imports

const Router = createConnectedRouter({
  getFound: store => store.get('found'), // <= ADD THIS ✨
  render: createRender({}),
});

export default Router;
```

And, yep that's exactly how to use createConnectedLink:
```
import { createConnectedLink } from 'found'

const Link = createConnectedLink({
  getFound: store => store.get('found'),
})

export default Link
```

**Comment by hollandThomas** [comment]
Man you guys are fast, thank you. It was a copy&paste error because I did some testing. I did in fact specify `getFound: state => state.get('found')`. Same errors.

**Comment by lukehedger** [comment]
Is `foundReducer` included in `/reducers/index` and actually in the store?

**Comment by hollandThomas** [comment]
yip, forgot to copy that bit

```
import { foundReducer } from 'found';
import { combineReducers } from 'redux-immutable';

import auth from './authReducer';
import newMessages from './newMessagesReducer';

export default combineReducers({
  foundReducer,
  auth,
  newMessages,
});
```

**Comment by lukehedger** [comment]
Ah, so it will be under key `foundReducer` in your store (`state.get('foundReducer')`)!

**Comment by NSLS** [comment]
btw, if anyone will try to accomplish this with SSR, make sure you don't convert found's data from server with Immutable.fromJS()

**Comment by hollandThomas** [comment]
oh wow. yeah that was pretty obvious, my bad :D 
sadly, after fixing this, it just throws infinite errors and freezes my chrome tab. Seems like its an infinite loop of "Cannot read property 'resolvedMatch' of undefined'

**Comment by hollandThomas** [comment]
When do you guys dispatch the farce actions? I suspect that the store's initial state is the problem. It seems that initially, found is null. Therefore resolvedMatch is null as well. As soon as @@found/UPDATE_MATCH is dispatched, everything is defined. That just doesn't stop the error from being thrown.

<img width="809" alt="bildschirmfoto 2017-10-24 um 14 16 41" src="https://user-images.githubusercontent.com/20690465/31942637-46740f14-b8c6-11e7-9632-70232bcee4b3.png">

**Comment by NSLS** [comment]
In my case I dispatch the init action on server, and the code looks like this

```
const store = createStore(client, new ServerProtocol(req.url));

store.dispatch(FarceActions.init());

const matchContext = {store};

let renderArgs;

try {
    renderArgs = await getStoreRenderArgs({
        store,
        matchContext,
        getFound: state => state.get('found'),
        resolver,
    });
} catch (e) {
    if (e instanceof RedirectException) {
        res.redirect(302, store.farce.createHref(e.location));
        return;
    }

    throw e;
}

const sheet = new ServerStyleSheet();

const component = (
    <StyleSheetManager sheet={sheet.instance}>
        <Wrapper
            context={context}
            store={store}
            locale={req.headers['accept-language']}
        >
            <RouterProvider router={renderArgs.router}>
                {render(renderArgs)}
            </RouterProvider>
        </Wrapper>
    </StyleSheetManager>
);

// And then send the response to the client with this component rendered to string
```

And on the client I have the following code

```
export default async (store) => {
    const matchContext = {store};

    const initialRenderArgs = await getStoreRenderArgs({
        store,
        matchContext,
        getFound: state => state.get('found'),
        resolver,
    });

    const ConnectedRouter = createConnectedRouter({
        render,
        getFound: state => state.get('found')
    });

    return props => (
        <Wrapper {...props}>
            <ConnectedRouter
                matchContext={matchContext}
                resolver={resolver}
                initialRenderArgs={initialRenderArgs}
            />
        </Wrapper>
    );
};
```

**Comment by hollandThomas** [comment]
I tried modifying the [foundReducer](https://github.com/4Catalyzer/found/blob/beee218b7e94c33a827b8ab8066f7b3a44c3f2c6/src/foundReducer.js) so that it is initialized with a simple { match:{}, resolvedMatch: {} } object. Does not change a thing. @taion any ideas?

**Comment by hollandThomas** [comment]
Okay never mind. I forgot to replace one instance of a Link component. 

There's one thing we could possibly learn from this: it would be nice to avoid an infinite loop of errors and instead throw each occurrence just once if possible. Maybe also some error message refinements like "this is probably caused by [...]". Thanks everybody!

**Comment by taion** [comment]
I'm not sure why you're getting an infinite error loop. Shouldn't the page just fail to render? What's making it re-render?

**Comment by hollandThomas** [comment]
This is what gets repeated infinite times:
<img width="814" alt="bildschirmfoto 2017-10-24 um 17 17 39" src="https://user-images.githubusercontent.com/20690465/31951864-75932640-b8df-11e7-9c72-0b70eb242db6.png">

It might be AppContainer from react-hot-loader? I don't know

**Comment by taion** [comment]
Might be a react-hot-loader thing with the re-render on exception, yeah.
