### ISSUE TITLE
Application Redux state might being replaced when using Router

### ISSUE THREAD

**Issue by gabrielgian** [4Catalyzer/found#135]
I thought Redux was not going to be needed in my React application, but now this need came and it seems Redux state is being replaced by found.

I can be wrong, but running this code:

`const mapStateToProps = state => {
  console.log(state);
  return { sidebar: state.sidebar };
};`

I got this output in console: 

`Object { found: Object }`

So I can't get the sidebar piece of state. My rootReducer is defined as:

`const rootReducer = combineReducers({
  sidebar: Sidebar
});`

Is there anyone who had this same problem?

**Comment by taion** [comment]
Take a look at https://github.com/4Catalyzer/found#createconnectedrouter.

Found works with an existing Redux store. You just need to create the router slightly differently and do a bit more of the store configuration yourself.

**Comment by gabrielgian** [comment]
Should I insert my reducers when creating the store for found? 

something like: 

`const store = createStore(
  combineReducers({
    found: foundReducer,
    ...reducers
  }),
  compose(
    createHistoryEnhancer({
      protocol: new BrowserProtocol(),
      middlewares: [queryMiddleware],
    }),
    createMatchEnhancer(
      new Matcher(routeConfig),
    ),
  ),
);`

Or I need a different Provider for my reducers?

**Comment by taion** [comment]
Same provider. The idea is just that you're installing the Found enhancers and reducers into your existing store, then using the same provider to drive Found as to drive the rest of your app. See e.g. the [Redux](https://github.com/4Catalyzer/found/tree/master/examples/redux) and [Universal Redux](https://github.com/4Catalyzer/found/tree/master/examples/universal-redux) examples.

**Comment by gabrielgian** [comment]
Ok, I got it.. Thanks for your help @taion !!!
