### ISSUE TITLE
Basename middleware with createConnectedRouter + createHistoryEnhancer

### ISSUE THREAD

**Issue by lukehedger** [4Catalyzer/found#137]
How can I pass a basename other than '/' to `createConnectedRouter` (when using a shared Redux store)?

**Comment by taion** [comment]
Use the `middlewares` option in `createHistoryEnhancer`.

**Comment by lukehedger** [comment]
The following throws the error `b.apply is not a function`
```
const basenameMiddleware = createBasenameMiddleware({ basename: 'xyz' })

createHistoryEnhancer({
  protocol: new BrowserProtocol(),
  middlewares: [queryMiddleware, basenameMiddleware],
})
```

**Comment by taion** [comment]
That's odd. Do you have a stack trace?

**Comment by lukehedger** [comment]
@taion Stack trace is here https://gist.github.com/lukehedger/c2bd318b01a99b0cac9fa38d95ce8241

**Comment by lukehedger** [comment]
Ah, so I just realised it causes the above error if the `basename` is `'/'` || `''`. Sorry for that confusion. It works fine if `basename` is set to another value.

So, it is possibly an error here: https://github.com/4Catalyzer/farce/blob/9d3ad263040e1c08ae10aa949064d56f34e3e21c/src/createBasenameMiddleware.js#L4

**Comment by taion** [comment]
I'm reopening this so I don't forget to fix the "dummy" case.
