### ISSUE TITLE
Redirect in renderError

### ISSUE THREAD

**Issue by baquy96** [4Catalyzer/found#139]
When I catch an error 401, I wanna redirect to /login.
I used compoent `Render` but an error occured: **Cannot call a class as a function** 
So, How to fix it.
`
render: createRender({

    renderError({ error }) {

      switch (error.status) {

        case 404:

          return <GenericError />;

        case 401:

          return <Redirect from="/diary" to="/login" />;

        default:

          return null;

      }

    }

  })
`

**Comment by taion** [comment]
You can't render a `<Redirect>`. It's only for configuration.

Instead, in your routes, instead of doing:

```js
throw new HttpError(401)
```

do:

```js
throw new RedirectException('/login');
```

In general it's too late to redirect when you're at the global render callback. It might work, but perhaps not in all cases.

**Comment by baquy96** [comment]
@taion It's works. Thank you so much
