### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by enricribas** [4Catalyzer/found#140]
I *think* this is coming from found, apologies if it is not, but very hard to track down.

I get this warning in my console.
```
Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package
```
with this code 
```
ReactDOM.render(
  <BrowserRouter resolver={resolver} />,
  document.getElementById('root')
);

```

where BrowserRouter is ...
```
import { makeRouteConfig, Route } from 'found';
import createFarceRouter from 'found/lib/createFarceRouter';
import queryMiddleware from 'farce/lib/queryMiddleware';
import BrowserProtocol from 'farce/lib/BrowserProtocol';
import createRender from 'found/lib/createRender';
import React from 'react';

import App from './containers/App';

export default createFarceRouter({
  historyProtocol: new BrowserProtocol(),
  historyMiddlewares: [queryMiddleware],
  render: createRender({}),

  routeConfig: makeRouteConfig(
    <Route path="/" Component={App} />
  ),
});

```

I do NOT get it if I render App directly as in ...

```
ReactDOM.render(
  <App />,
  document.getElementById('root')
);

```
Probably going to feel stupid when I find the issue but **seems** to be related to either found or farce.
On...
    "farce": "^0.2.3",
    "found": "^0.3.5",

**Comment by taion** [comment]
I haven't seen this issue here before. Could you:

- Check the version of React you're using
- Set a breakpoint there and share the stack trace?

**Comment by enricribas** [comment]
react@15.4.2

ok, it seems the problem is (was) ...
-    "webpack-stats-plugin": "^0.1.4"

not sure why removing browserRouter also fixed the problem, but removing this gem stopped the issue!
And we can continue to use found without going crazy. :)
Thanks,
