### ISSUE TITLE
how to get the location(url)

### ISSUE THREAD

**Issue by Ai01** [4Catalyzer/found#141]
l want to know how to get the current location(the url of the page).All l found is the matcher which has a routerConfig.
l'm already search in goole. thank you for help

l know l can get the location in props.But how to get the location by the router in context?

**Comment by taion** [comment]
Wrap your component with `withRouter()` and use `props.match.location`.

**Comment by MapleYe** [comment]
Here's how I get the url of  the current page
```
const { match } = this.props;
const path = match.location.pathname;
```
