### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by rosskevin** [4Catalyzer/found#142]
Hello @taion,

Are you interested in [bundling a typescript definition file in the package](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)?  I have created/documented one and could submit it with a PR if you like.

**Comment by taion** [comment]
cc @jquense @itajaja who have worked more with TS than me

It seems like a good idea, but I don't really understand the trade-offs here. What are the pros and cons of bundling TS defs here?

**Comment by rosskevin** [comment]
I don't think there are any consequences for non-typescript users. For TS users, definitions will automatically be picked up. We bundle them in the material-ui project and it works well.

Arguably the advantage is the TS file bundled here is versioned the same as the distributed code.

**Comment by taion** [comment]
Hmm, is the drawback that if I forget to update the TS defs, or otherwise mess them up, that I'll have to cut a new release to fix them?

**Comment by rosskevin** [comment]
Yes, but that's no different than would occur in the definitely typed repo. I think there is a higher likelihood of community engagement/maintenance in-repo.  So while it would be nice if you thought about changes in the .d.ts file when you made them, I understand this to be something that I and others will maintain here, with the extra value of you spotting problems in PRs since you are the authority on the codebase.

My argument is based on the ease of submitting/accepting a PR here versus the same at definitely typed.

**Comment by rosskevin** [comment]
I should also mention, it is very easy for TS users to patch (augment) existing definitions in the case a release had an error in the definitions file.

So there isn't necessarily a burning need to cut a new release in x hours due to a mistake.

**Comment by taion** [comment]
Okay, if it's easy for users to patch locally, then that sounds fine. I was worried about being in a position where people needed a new release to e.g. fix typing bugs, but I had conflicting deadlines.

**Comment by rosskevin** [comment]
Ok, when I'm done with a once-over in my code I'll PR.  Probably a day or two.

**Comment by taion** [comment]
Thanks!

**Comment by itajaja** [comment]
> I should also mention, it is very easy for TS users to patch (augment) existing definitions in the case a release had an error in the definitions file.

@rosskevin how so? you'd have to vendor the definition, patch it manually, and then mess with the tsconfig.json to point to your vendor folder instead of (or in addition to) `node_modules`. Am I missing something? 

Other than that, I would suggest adding a PR github template so that people creating a PR are reminded to update the ts defs

**Comment by rosskevin** [comment]
Luckily this case is well considered and you don't need to touch the vendor file.  Please see https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Example that merges `FormData` onto global `Window`:

`tsconfig.json`:

```json
{
  "include": [
    "typings",
    "src"
  ],
}
```

`typings/lib.d.ts`:

```js
interface Window {
  FormData: FormData
}
```

**Comment by itajaja** [comment]
TIL :) although it's only additive, it's probably enough to make the compiler happy and preserve some type safety
