### ISSUE TITLE
Hot Reloading Failed for ConnectedRouter

### ISSUE THREAD

**Issue by MapleYe** [4Catalyzer/found#145]
Everything works well right after first loading. But once I change something in my jsx code and HMR starts to replace modules, the following error occurs:

<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically.

I think it is caused by store.dispatch(FarceActions.init()) after creating a redux store.

**Comment by MapleYe** [comment]
Figured it out: make redux Provider new on hot reloading can solve the warning. 
`<Provider key={Math.random()} store={store}>
        <ConnectedRouter resolver={new Resolver(environment)} />
    </Provider>`

**Comment by MapleYe** [comment]
Figured it out: make redux Provider new on hot reloading can solve the warning.
`<Provider key={Math.random()} store={store}>
        <ConnectedRouter resolver={new Resolver(environment)} />
    </Provider>`

**Comment by taion** [comment]
That works, but it will wipe out your store state.

Eventually https://github.com/4Catalyzer/found/issues/104 will add better support for something like this.

**Comment by MapleYe** [comment]
Thanks, taion. I'll check it out.

**Comment by taion** [comment]
I'm adding first-class support for reloading route configs in https://github.com/4Catalyzer/found/pull/152.
