### ISSUE TITLE
Retrieving query parameters using Link component

### ISSUE THREAD

**Issue by dlcoffee** [4Catalyzer/found#147]
I'm working on a new project and am a little unfamiliar with this routing library. I'm trying to pull the query parameters from a route in a component.

Route:
```javascript
<Route
  path="/foo"
  getComponent={lazyLoadFooPage}
  getQuery={require('../queries/FooPage').default}
/>
```

 I'm using `Link` as so:
```javascript
<Link to={{ pathname: '/foo', query: { bar: 'baz' } }} />
```

When I click on the rendered `a` tag, I'm taken to `/foo?bar=baz`, but I'm unable to retrieve the query parameters from the `FooPage` component. I'm sort-of guessing it has to do with the `getQuery` defined in the route, but I'm unable to find any documentation about it.

**Comment by taion** [comment]
You need to use `prepareVariables`. See https://github.com/4Catalyzer/found-relay/blob/ceb1195a9cf1eb25806a2b44c26454d853714f89/test/modern/Resolver.test.js#L121-L124
