### ISSUE TITLE
memory or alternative router

### ISSUE THREAD

**Issue by dvdschwrtz** [4Catalyzer/found#148]
Hi guys, I am hoping to use found-relay and react-relay inside a chrome extension, but I don't want to use browser routing, instead I would like to use memory routing or some other solution. Do you huys have any advice on how to do this? I was looking at this example from the docs to get started https://github.com/4Catalyzer/found-relay/blob/master/examples/todomvc-modern/src/client.js

**Comment by taion** [comment]
It'd be `MemoryProtocol` in Farce. @jquense did you ever code up something like that?

**Comment by jquense** [comment]
I didn't write a hash protocol but i have a Memory one that works for electron. let me PR that over...

**Comment by taion** [comment]
ref https://github.com/4Catalyzer/farce/pull/44

**Comment by taion** [comment]
Implemented as `MemoryProtocol` in Farce v0.2.4.

**Comment by dvdschwrtz** [comment]
Thanks guys. Appreciate the direction
