### ISSUE TITLE
BaseLink activePropName prop Boolean value causes a warning in React 16

### ISSUE THREAD

**Issue by lukehedger** [4Catalyzer/found#156]
The [`activePropName`](https://github.com/4Catalyzer/found/blob/a5777205c60f9b52811df6361c701d88ff8c535b/src/BaseLink.js#L99-L101) prop on the `BaseLink` component causes [a warning in React 16](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html) due to being assigned a Boolean value.

For example, this component:
```
<Link to='/' activePropName='active'>
```

will produce this warning:
```
Warning: Received `true` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="true" or active={value.toString()}.
```

As the warning message suggests, this can be solved by changing the prop value from a Boolean to a String.

**Note**: this can also be solved without a change to the codebase by using a `data` attribute:
```
<Link to='/' activePropName='data-active'>
```

**Comment by taion** [comment]
@lukehedger 

How does this come up, though? `activePropName` is really for custom components that take a prop for whether they're active. For e.g. React-Bootstrap integration, I'd use:

```js
<Link Component={NavItem} activePropName="active">
```

What's the point of passing a custom prop with the boolean active value into a DOM component?

**Comment by lukehedger** [comment]
@taion - it is a feature of React 16

> In React 16, we are making a change. Now, any unknown attributes will end up in the DOM:
```
// React 16 output:
<div mycustomattribute="something" />
```

So, the [returned component in `BaseLink.js`](https://github.com/4Catalyzer/found/blob/a5777205c60f9b52811df6361c701d88ff8c535b/src/BaseLink.js#L105-L110) will look like:
```
<a href="/to" active=true>...</a>
```

This in itself is fine but the fact that the value of the prop that ends up in the DOM is a Boolean causes the warning.

**Comment by taion** [comment]
Right, but why would you do `activePropName="active"` if you know you're rendering an `<a>`? Like why wouldn't you just do `<Link to="/">Whatever</Link>`?

**Comment by lukehedger** [comment]
Sorry, I'm not sure I understand your point - I thought you would do `activePropName="active"` so that you could apply some conditions to the `<a` element rendered by `<Link to="/">Whatever</Link>` when the route is `/`?

**Comment by taion** [comment]
Not exactly. The idea is that if you had something like:

```js
function MyLink({ active, className, ...props }) {
  return (
    <a
      {...props}
      className={classNames('my-link', active && 'active')}
    />
  );
}
```

Then you could render something like:

```js
<Link Component={MyLink} activePropName="active">
```

If you were just using an `<a>`, then instead you might do something like:

```js
<Link activeClassName="active">
```

Or something like:

```js
<Link activeStyle={{ color: 'red' }}>
```

**Comment by lukehedger** [comment]
Ah ok, I see - so you would _always_ used `activePropName` with the `Component` prop and a custom anchor?

**Comment by taion** [comment]
Yeah, I mean, it's the sort of thing that should probably take functional children like:

```js
<Link to="/">
  {active => <NavItem active={active}>Whatever</NavItem>}
</Link>
```

But `activePropName` is less typing, and this is a fairly common pattern anyway.
