### ISSUE TITLE
Matcher uses deprecated features from path-to-regexp.

### ISSUE THREAD

**Issue by CarlRosell** [4Catalyzer/found#159]
First: Thank you so much for all the work you put into this package and all your other packages for routing and relay 👍

When updating path-to-regexp, I noticed that the Matcher was using the `keys` directly from the returned `regexp` (https://github.com/4Catalyzer/found/blob/master/src/Matcher.js#L115). This "feature" was removed in this PR https://github.com/pillarjs/path-to-regexp/pull/114 and released in the 2.0.0 release.

**Comment by taion** [comment]
Great, thanks! I can't upgrade to Path-to-RegExp v2 quite yet, as that would constitute a breaking change, but this will be great prep work.
