### ISSUE TITLE
Route params with special characters

### ISSUE THREAD

**Issue by caioflores** [4Catalyzer/found#161]
There's a way to pass attributes with some special caracters as params in routes? Something like "sl_bill.CD.PLP.100.2011".

We use this format to our ids, but when I try to pass it as param I get an error.

Our route:
`<Route path="/bill/:id" Component={Bill}>`

The url will be something like this: localhost/bill/sl_bill.CD.PLP.100.2011

**Comment by taion** [comment]
What are the special characters there? They seem like URL-safe characters to me. Otherwise, you might need to URL encode the string.

**Comment by brunolemos** [comment]
I believe the problem is that the dot is considered a delimiter by default just as a `/` by the library https://github.com/pillarjs/path-to-regexp

The library accepts a `delimiters` option to change this but `Found` does not provide a way to pass options. It hardcodes the `{ end: true }` option only: https://github.com/4Catalyzer/found/blob/df37e58d7b674c7aecc2db181044a31ce09b54ea/src/Matcher.js#L108

**Comment by brunolemos** [comment]
> when I try to pass it as param I get an error.

@caioflores Which error?

I just tested with your ID and it works fine:

```js
const found = require('found')
const matcher = new found.Matcher()

matcher.matchRoute({ path: '/a/:id' }, '/a/sl_bill.CD.PLP.100.2011')
// output: { params: { id: 'sl_bill.CD.PLP.100.2011' }, remaining: '' }
```

**Comment by caioflores** [comment]
The dots (.) are the problem. When I try to access the page I get a blank page with: Cannot GET /app/bill/sl_bill.CD.PLP.100.2011

But when I change my url to something without dots like sl_bill!CD!PLP!100!2011, it works fine!

This are my routes:

`<Route path="/app" Component={App}>
      <Route path="/dashboard" Component={Dashboard} />
      <Route path="/legislativeData" Component={LegislativeData} />
      <Route path="/bill/:id" Component={Bill}>
    </Route>`

**Comment by taion** [comment]
@caioflores 

I'm not sure that I want to expose configuring the delimiters, as disabling slashes as delimiters could be a footgun.

What if you do something like `:bill(.*)` (or `:bill([^\\/])`)? I mean just use the custom regex bit per https://github.com/4Catalyzer/found#route-configuration.

**Comment by caioflores** [comment]
@taion 

Using bill(.*) I got the same error, I think I'll have to encode the string and decode in the component.

**Comment by taion** [comment]
What exactly is the error?

**Comment by caioflores** [comment]
I get this error when I put any dot in the url

<img width="899" alt="screen shot 2018-01-24 at 17 35 17" src="https://user-images.githubusercontent.com/4183877/35353021-0683483e-012d-11e8-9ee0-529e43c7914c.png">

**Comment by taion** [comment]
That error looks like it's coming from webpack dev server, no?

**Comment by caioflores** [comment]
@taion good point, maybe it is... I'll take a look

**Comment by caioflores** [comment]
It was a webpack problem guys, sry!

I found my problem here: https://github.com/webpack/webpack-dev-server/issues/454

I'll close the issue.
