### ISSUE TITLE
Support custom `context`

### ISSUE THREAD

**Issue by macalinao** [4Catalyzer/found#162]
I am using isomorphic-style-loader and need to inject an `insertCss` function into the context of each component. Afaik this is not possible with found-- please let me know if I am wrong. Thanks.

**Comment by taion** [comment]
You mean like React context? If you need context you can just render it outside of the `<Router>`, or if the context provider needs router context, you can also render it inside the router-level `render` callback.

**Comment by macalinao** [comment]
Thanks. I got confused with the `matchContext` section in the documentation -- I ended up making a component to wrap the `element` returned from `getFarceResult`.

**Comment by taion** [comment]
Right, yeah. I couldn't really think of a better name there. `matchContext` is context for matching, not for rendering.
