### ISSUE TITLE
How to use "AuthorizedRoute" server side.

### ISSUE THREAD

**Issue by cellis** [4Catalyzer/found#164]
Hello! First of all, thanks for a great library. It works really well with relay and SSR. But I have a question about how to do authorized routes. I had a read through https://github.com/4Catalyzer/found/issues/73 and managed to get my SSR routes working, like this:

```javascript
export default req =>
  class AuthorizedRoute extends Route {
    render({ Component, props }) {
      let jwt;

      if (process.env.IS_CLIENT) {
        jwt = Cookies.get('jwt');
      } else {
        jwt = req.cookies.jwt;
      }

      if (!jwt) throw new HttpError(401);

      return Component && props ? (
        <Component {...props} />
      ) : (
        <div>
          <small>Loading</small>
        </div>
      );
    }
  };

```

Note that I need access to the `req` in order to get cookies on the server side, leading me to return the class with a req closure. It works fine, but as I'm a solo dev and I don't know anyone else using this router, I'm wondering if this a sane approach, or am I missing something?

**Comment by taion** [comment]
This is a fine approach, but what's even better would be to use the `matchContext` feature: https://github.com/4Catalyzer/found#data-or-getdata

When you render your `<Router>` or call `getFarceResult`, just pass in e.g. a `getJwt()` callback on `matchContext`, then in `render` call `match.context.getJwt()`. That way, you don't need to create different instances of your route classes for each request, and you can inject something totally different for `getJwt()` for testing.
