### ISSUE TITLE
Appears error whenever app renders Link component

### ISSUE THREAD

**Issue by noone0012** [4Catalyzer/found#168]
![untitled](https://user-images.githubusercontent.com/25947677/36728934-e3c50fac-1bdb-11e8-9d7d-8c9234cb58c2.png)

Manually navigating works perfectly but whenever app renders Link component this error appears.
I'm using it with found-relay, here are screenshoots.

index.js
![index](https://user-images.githubusercontent.com/25947677/36729443-a323b7ee-1bdd-11e8-8ba6-c8e961a4ed20.png)

router.js
![router](https://user-images.githubusercontent.com/25947677/36729444-a34e4108-1bdd-11e8-87d2-44b34a7c9717.png)

routes.js
![routes](https://user-images.githubusercontent.com/25947677/36729446-a378326a-1bdd-11e8-8c5b-61664ce011da.png)

**Comment by taion** [comment]
Do you have your own Redux store and provider in `<App>`?

**Comment by noone0012** [comment]
yes. http://prntscr.com/ikg3se

**Comment by noone0012** [comment]
oh, I've just moved the provider into index.js and it now works!  Thank you so much!

**Comment by taion** [comment]
That's not going to work either. Use https://github.com/4Catalyzer/found#createconnectedrouter.
