### ISSUE TITLE
createHref function returning undefined in BaseLink

### ISSUE THREAD

**Issue by pradyuman** [4Catalyzer/found#175]
This results in no href on any found Link.

**Comment by taion** [comment]
How are you hitting this?

**Comment by pradyuman** [comment]
I'm using Link like this:
```
<Link to={`/${region.toLowerCase()}`}>
  <img src={logo} />
  <span styleName="title">
       Legends.ai
  </span>
</Link>
```

within a class that's wrapped in withRouter. The router does exist (I console.logged inside BaseLink in the found library) but the createHref is returning undefined.

**Comment by taion** [comment]
Is `createHref` itself defined? How are you configuring your router?

**Comment by taion** [comment]
Any updates?

**Comment by pradyuman** [comment]
Sorry for the late reply-- I was traveling for business. We are using found relay with server side rendering.

createHref is defined as:
```
ƒ () {
  return dispatch(actionCreator.apply(undefined, arguments));
 }
```
when I console.log.

**Comment by taion** [comment]
Sure, so that's what it should look like. How are you setting up your router and history?

**Comment by mkaradeniz** [comment]
We also had this problem. The fix was inside one of our _own_ Redux middlewares that called `next(action);` before returning. Instead of returning the `next(action)` call.

```diff
- next(action);
- return;
+ return next(action);
```

**Comment by taion** [comment]
Most likely this is coming from the bad middleware per the above. Closing this out for now.
