### ISSUE TITLE
Refresh getData

### ISSUE THREAD

**Issue by mickeyreiss-visor** [4Catalyzer/found#184]
What is the recommended way to refresh data provided to the component via `getData`? Is it possible for the component to ask `found` to reload its data? 

I think this approach would allow me to use component data exclusively, removing the need for redux or any other data caching layer.

**Comment by taion** [comment]
Well, the easiest way right now is to just run a "replace" transition to the same location. That would reload all the data, though.

Is the idea that you want something like a `refetch` or `retry` callback that gets passed down to a component that will retry the fetch?

**Comment by mickeyreiss-visor** [comment]
Yes, that would be one way. 

The root of my question was, is it possible to use this library without redux in a data-driven app?

For read-only pages, it’s quite simple. For pages with a small writes, I imagine my code turning into something like jquery spaghetti.

**Comment by mickeyreiss-visor** [comment]
Thanks for the response and workaround. Closing for now as it seems I have an answer. Fee free to reopen if you feel this would be an interesting area for future versions of the library.

**Comment by taion** [comment]
What did you go with for now? Just re-running routing?

I do think this is an interesting idea, but currently, with Found by itself (i.e. not with Found Relay or something), we don't currently render any components other than the route components, outside of the `<Router>` itself.

The most natural way would be to have some component corresponding to each route, that could then hold onto the `getData` state, and pass it down.

Perhaps the most natural way to do this would be to have some sort of `<RetryProvider>` that can be used at a per-route level.

**Comment by mickeyreiss-visor** [comment]
@taion For now, I am not using `Data`/`getData`, but instead, I am using a more standard redux approach inside of my "routed" components.
