### ISSUE TITLE
pathname trailing slash

### ISSUE THREAD

**Issue by MartinDawson** [4Catalyzer/found#187]
Related to [PR 100](https://github.com/4Catalyzer/found/pull/100) I think.

We have a problem because `pathname` accepts trailing slashes so:

`/projects/` and `/projects`. We then build a url off of this pathname, e.g: `${location.pathname}/users` but the problem we are having is that we are getting double slashes on the end if the user typed in `/projects/` manually which is causing a 404.

Would it not make sense for pathname to treat just remove slashes from the end? If not then where would be a good place to add this logic globally in found so we don't have to transform the `pathname` in each place manually?

**Comment by taion** [comment]
It's an option, but I wasn't sure I wanted to be that opinionated. Have you considered using https://github.com/4Catalyzer/found/blob/d2efc3ba6a6bba2bc83f80fb4c5f9624c35db7de/src/Matcher.js#L36-L47 to do the join in this case?

**Comment by MartinDawson** [comment]
@taion We can do that. Thanks.

**Comment by taion** [comment]
The other thing you can do is to always redirect to the slash-free version... either throw a redirect in your router or use a Redux middleware in the nav/routing stack. I thought this was too opinionated to do out-of-the-box, though, and most websites seemed to tolerate but keep extraneous trailing slashes.

**Comment by MartinDawson** [comment]
adding `<Redirect from="(.*/)" to={({ location }) => location.pathname.slice(0, -1)} />` to the top of my route config worked well. 

Thanks.
