### ISSUE TITLE
getFarceResult vs getStoreRenderArgs

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#194]
How is `getFarceResult()` approach compared to the `getStoreRenderArgs()` approach?
Why would someone choose the complicated `getStoreRenderArgs()` approach instead of the simple `getFarceResult()` approach?
If just `getStoreRenderArgs()` is used will it work with an application that's already using Redux?
Or will it create its own separate Redux, or will it not use Redux at all, or what will happen?

**Comment by catamphetamine** [comment]
Ok, I guess it won't use Redux at all with just `getFarceResult()`.

**Comment by taion** [comment]
`getStoreRenderArgs` takes the existing `store` as an argument, so it works with the existing store.

The point of `getStoreRenderArgs` is exactly just to work with an application that's already using Redux.
