### ISSUE TITLE
Hash routing with memory router

### ISSUE THREAD

**Issue by MartinDawson** [4Catalyzer/found#195]
I am creating a google extension and therefore using the MemoryRouter.

I want to use hash routing to be able to differentiate my routes. The reason for this is that I do not have control over the routes because it's an extension.

for example this route: https://github.com/everestate/everestate#onboardor

with this config:

```js
export default makeRouteConfig(
  <Route path="/">
    <Route path="/everestate/everestate#onboardor" {...dashboardRouteConfig} />
  </Route>,
);
```

Doesn't work. Is this possible?

Here's what I was doing before:

```js
export default makeRouteConfig(
  <Route path="/">
    <Route path="/everestate/everestate" {...dashboardRouteConfig} />
  </Route>,
);
```

```js
import Dashboard from "./dashboard";
import { IRoute } from "../../../Components/types";
import React from "react";
import { graphql } from "react-relay";

const query = graphql`
  query dashboardContainerQuery {
    organizations {
      id
      name
      avatarUrl
    }
  }
`;

export const routeConfig = {
  Component: Dashboard,
  query,
  render: (route: IRoute) => {
    if (route.props &&
      route.props.location.hash === "#onboardor") {
        return <Dashboard {...route.props} />
    }
    return null;
  },
};

export default Dashboard;
```

The problem with this is that the query gets run even if it's not needed.

It the best way to do this to do something like this:

```js
export const routeConfig = {
  Component: Dashboard,
  query: ({ route }) => route.props.location.hash === "#onboardor" ? query : null,
};

```

Or should I change to `hashProtocol` in farce or a different type of url routing?

Thanks!

**Comment by gilles-yvetot** [comment]
@MartinDawson I am actually also developing a chrome extension and I do not understand why but the MemoryRouter is adding a `#`

**Comment by taion** [comment]
I don't think it is. Are you sure you're using `MemoryProtocol`? `MemoryProtocol` doesn't interact with any browser APIs at all.

**Comment by gilles-yvetot** [comment]
@taion thanks for the quick answer. My problem was I was still creating a hash history even though I was not using it. And creating it was adding a `#` in the URL
