### ISSUE TITLE
What is `render` property?

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#199]
The server-side rendering section provides the code example:

```js
<Provider store={store}>
  <RouterProvider router={renderArgs.router}>
    {render(renderArgs)}
  </RouterProvider>
</Provider>
```

But it doesn't say where is `render` variable taken from.
Where can `render` function be obtained?
Or must it be created manually?
If yes, what must it do and what must it return?

**Comment by taion** [comment]
It's the output of `createRender`; see https://github.com/4Catalyzer/found/blob/master/examples/universal/src/render.js in the SSR example.

**Comment by catamphetamine** [comment]
Ok, thx, seems that I finally figured it out.
The documentation is not easy to read, but after reading it several times one can figure most of it out.
My non-tested implementation is as follows.
I'll test it next week.

#### render.js
```js
import createRender from 'found/lib/createRender'

export const render = createRender({
	renderError: ({ error }) => <div> Error </div>
})
```

#### client.js

```js
export { default as HistoryProtocol } from 'farce/lib/BrowserProtocol'

import { ScrollManager } from 'found-scroll'
import getStoreRenderArgs from 'found/lib/getStoreRenderArgs'
import createConnectedRouter from 'found/lib/createConnectedRouter'
import resolver from 'found/lib/resolver'
import render from './render'

export function matchRoutes(store) {
	return getStoreRenderArgs({
		store,
		resolver
	})
}

export function createRouterElement(initialRenderArgs) {
	const ConnectedRouter = createConnectedRouter({
		render: (renderArgs) => (
			<ScrollManager renderArgs={renderArgs}>
				{render(renderArgs)}
			</ScrollManager>
		)
	})
	return (
		<ConnectedRouter
			resolver={resolver}
			initialRenderArgs={initialRenderArgs}/>
	)
}
```

#### server.js

```js
export { default as HistoryProtocol } from 'farce/lib/ServerProtocol'

import { getStoreRenderArgs, RedirectException, resolver } from 'found'
import { RouterProvider } from 'found/lib/server'
import render from './render'

export function matchRoutes(store) {
	return getStoreRenderArgs({
		store,
		resolver
	}).then(
		(renderArgs) => {
			if (renderArgs.error) {
				return Promise.reject(renderArgs.error)
			}
			return { renderArgs }
		},
		(error) => {
			if (error instanceof RedirectException) {
				return {
					redirect: store.farce.createHref(error.location)
				}
			}
			return Promise.reject(error)
		}
	)
}

export function createRouterElement(renderArgs) {
	return (
		<RouterProvider router={renderArgs.router}>
			{render(renderArgs)}
		</RouterProvider>
	)
}
```

**Comment by taion** [comment]
There are two fully-working SSR examples included here. Please follow those for more detail: https://github.com/4Catalyzer/found#examples

**Comment by catamphetamine** [comment]
Ok.
Question about the example in the README:

```js
app.use(async (req, res) => {
  /* ... */

  let renderArgs;

  try {
    renderArgs = await getStoreRenderArgs({
      store,
      matchContext,
      resolver,
    });
  } catch (e) {
    if (e instanceof RedirectException) {
      res.redirect(302, store.farce.createHref(e.location));
      return;
    }

    throw e;
  }
});
```

So `getStoreRenderArgs()` performs routing, but how is it gonna know which `location` should it match routes against?
You don't pass `req.path` anywhere.

**Comment by catamphetamine** [comment]
nvm, I see it in the `universal-redux` example now: so the store is supposed to be initialized with `new ServerProtocol(req.path)` first.

**Comment by catamphetamine** [comment]
@taion 
I noticed that `farce` has an asynchronous `addTransitionHook`, and yet `found` doesn't use it for `getData()`.
What was your reasoning behind this?
You could implement it to run `resolver()` in a transition hook.
Yet you chose another way: AFTER the location is updated `found` runs `resolver()` and then updates the markup.

**Comment by catamphetamine** [comment]
@taion 
Also, I was looking into implementing my own `resolver`.
As far as I can see the only public method of `resolver` is `resolveElements(match)`.
What must it return?
You declare it as `async * resolveElements(match)` but what is it in terms of `Promise`?
Must it resolve a `Promise`? Or an array of `Promises`? Or must it be a generator?

**Comment by jquense** [comment]
It's an async generator, which is a generator where each call to .next() returns a promise for the next value

**Comment by jquense** [comment]
https://github.com/tc39/proposal-async-iteration

**Comment by catamphetamine** [comment]
@jquense Wouldn't it be simpler if all generators were rewritten as Promises instead?

**Comment by catamphetamine** [comment]
@jquense Ok, I found a workaround: instead of supplying a custom `resolver` I simply place an `async getData()` on the top route and it works the same way. Except that I don't have to decypher the cryptic "generator" syntax. Otherwise I'd switch to another library because no one wants to deals with "generators" nowadays.

**Comment by jquense** [comment]
Nowadays? :P it's brand new to the language

**Comment by catamphetamine** [comment]
@jquense 
> Nowadays? :P it's brand new to the language
Yeah, they are "brand new" if you're still in 2015.
https://ponyfoo.com/articles/es6-generators-in-depth
No one uses "generators" nowadays.
I recommend your library be migrated to human-readable `Promise`s.

**Comment by jquense** [comment]
async iteration is still a proposal, you'r thinking of plain generators. I also think you may misunderstand the use-cases for generators, having probably only ever seem them used as a sort of poor man's async/await via `co` or similar. This is a great example of where they work well, the equivalent code in resolveElements written with only promises would be orders of magnitude more complicated than the async iterator. Promises and generators are different things that have different use-cases, this isn't really a good fit for plain promises, as it's a stream of async values, not a single one.

**Comment by catamphetamine** [comment]
@jquense 
> the equivalent code in resolveElements written with only promises would be orders of magnitude more complicated than the async iterator.

Now that's the answer.
No questions then.
If it really simplifies code a lot then your usage of generators there is justified.
If it doesn't then it's not.
I'll assume what you're saying is true.

**Comment by catamphetamine** [comment]
It still doesn't negate the fact that no one will be passing their custom `resolver` due to the complexity of doing that.
If it was just a function returning a `Promise` then it would be easy.
Otherwise no one will bother doing that.
Anyway, `async getData` on the root `Route` seems to work for me.
Thanks.

**Comment by taion** [comment]
That's correct. Just to reiterate, custom resolvers should only be required for new data integrations. Otherwise, per the examples, add `getData` methods to your routes that return promises.

**Comment by catamphetamine** [comment]
@taion @jquense 
Question: suppose there's a `<Route/>` with `path="/users/:id"`.
Suppose there are `<Link/>`s on `<UserPage/>` to the currently viewed user's "friends" (like in a social network).
Hence the transition is gonna be performed from the same `<Route/>` to the same `<Route/>`, just with another `:id` parameter.
In this case the `<UserPage/>` element doesn't get unmounted and then re-mounted, instead it survives the navigation.
Do you consider this a bug?
Or is it intended behaviour? If that's intented then what workaround would you propose for detecting such transitions and forcing component remount (e.g. via a `key`).
There was a similar issue with `react-router`: https://github.com/ReactTraining/react-router/issues/1982
I solved it via `key = `${location.pathname}${location.search}`:
https://github.com/ReactTraining/react-router/issues/1982#issuecomment-275346314

**Comment by taion** [comment]
Yes – the point is we want things to work the way that React components normally work, so that the typical lifecycle hooks continue to work. You can always randomize the key (or use the location key as the component key) if we keep things the same, but you can't keep the component if we always re-mount it.

**Comment by catamphetamine** [comment]
@taion 
Ok, I didn't understand your answer but whatever.
Here's my solution, for reference:

```js

export function createRouterElement(renderArgs, getState) {
	const ConnectedRouter = createConnectedRouter({
		render: (renderArgs) => {
			const newLocationLoaded = !getState().preload.pending
			const location = newLocationLoaded ? renderArgs.location : getState().found.resolvedMatch.location
			const key = window.reactWebsiteRemountOnNavigate === false ? undefined : `${location.pathname}${location.search}`
			return (
				<ScrollManager renderArgs={renderArgs}>
					<RemountOnNavigate key={key}>
						{render(renderArgs)}
					</RemountOnNavigate>
				</ScrollManager>
			)
		}
	})
	return (
		<ConnectedRouter
			resolver={resolver}
			initialRenderArgs={renderArgs}/>
	)
}

function RemountOnNavigate(props) {
	return props.children
}
```

**Comment by catamphetamine** [comment]
Actually, I found a better way of re-mounting: instead of re-mounting the whole `<Route/>` tree only the last `<Route/>` is re-mounted.
And also the `key` is only `location.pathname`, without `location.search`, because if `location.search` caused re-mount then changing search filters on a search page would re-mount the whole page (because changing search filters updates the URL with search parameters).

```js
export function createRouterElement(renderArgs, getState) {
	const ConnectedRouter = createConnectedRouter({
		render: (renderArgs) => {
			// Force re-mount the last `<Route/>` component on location path change.
			const elements = renderArgs.elements
			if (elements && window.reactWebsiteRemountOnNavigate !== false) {
				elements[elements.length - 1] = React.cloneElement(elements[elements.length - 1], { key: renderArgs.location.pathname })
			}
			return (
				<ScrollManager renderArgs={renderArgs}>
					{render(renderArgs)}
				</ScrollManager>
			)
		}
	})
	return (
		<ConnectedRouter
			resolver={resolver}
			initialRenderArgs={renderArgs}/>
	)
}
```

**Comment by catamphetamine** [comment]
@taion @jquense 
> This is a great example of where they work well, the equivalent code in resolveElements written with only promises would be orders of magnitude more complicated than the async iterator. 

So what's the deal with all those generators in `resolveElements`?
What's so special about them.

As far as I saw, first it looks for "early components" (whatever that is) and "early data" (whatever that is).
Presumably that is some kind of a minor optimization for `getComponents` and `getData` which are fake and are something like `Promise.resolve(data)`.
After the "early" stuff is sorted out, it creates `pendingElements` which is like the regular `elements` but with `null`s where there are unresolved `Component` or `data`.
Then there's this mysterious line:

```js
yield pendingElements.every(element => element !== undefined)
        ? pendingElements
        : undefined;
```

So what's so special about this line?
What does it do?
Does it simply return `pendingElements` if it contains no `undefined` items?
If yes, then this means that the use-case for "generators" here is to return `elements` two times instead of one time for the synchronous use-case: the first time it returns all elements prematurely available and the second time it returns all elements after they have been resolved.
I guess it doesn't return more than two times?
E.g. as some components/data get resolved it would return elements with the currently resolved components/data.
I.e. this is theoretically possible but no one actually needs that feature.

**Comment by catamphetamine** [comment]
@taion 
So, this leads me to a point: if I place my root `getData` on the root `<Route/>` and expect it to receive all `routes` having `Component`s set then I guess it's what happens with the regular `Component={...}` synchronous approach and *that's now what happens* with the asynchronous `getComponent={...}` approach.

I.e. suppose I have `getData` set up on the root `<Route/>`.
Next, suppose that root `<Route/>` has a `Component={...}` set and some other leaf `<Route/>` (the actual page) has `getComponent={...}` property set.
So what happens is that the root `getData` only gets called a single time and it doesn't get all the `route.Component`s because some of them are `null` due to not being resolved at that time.
Then, when all those unresolved components resolve themselves they're re-rendered, but the root `getData` property doesn't get called the second time?
And what if `getData` needs the full `route.Component` chain?

**Comment by catamphetamine** [comment]
And also this line:

```js
      yield pendingElements.every(element => element !== undefined)
        ? pendingElements
        : undefined;
```

It should have been written differently, not discarding the whole elements chain and instead just trimming it so that `undefined` elements are not part of it.

**Comment by catamphetamine** [comment]
@taion 
I performed some tests and I found out that on server side it waits for everything to resolve which is correct.
And I also found out that the root `getData` won't be called after everything loads which means I'll have to move my code from the root `getData` somewhere else.
I'll post here if I find a suitable place for it (i.e. when all `getComponent` calls are resolved).

**Comment by catamphetamine** [comment]
@taion 
After some thinking I decided that I shouldn't be fighting `found` in this aspect and rewrite my code to leverage `getData` and `defer` (made available by a contributor).
Previously I wrote my own "preload chain" tool collecting static `getData` methods from route components which conceptially is the same what `found` already has built-in.

**Comment by catamphetamine** [comment]
@jquense 
> the equivalent code in resolveElements written with only promises would be orders of magnitude more complicated than the async iterator. 

So, turns out that `resolveElements` is only using generators to return several times from a method.
And now that I found that out I can conclude that your "orders of magnitude more complicated" statement is clearly wrong and intentionally deceptive.
Returning an infinite iterator from a function using pure `Promise`s is a very simple thing via `{ value: any, hasNext: boolean, next(): function }`.
So you clearly don't understand too much how `Promise`s really work and what they're capable of.
And you're spreading false statements left and right.
I guess your developer skill level is above average maybe, but not higher.
I'll assume all your statements as being falsy from now on.
