### ISSUE TITLE
Nested Routes config

### ISSUE THREAD

**Issue by MrSumant** [4Catalyzer/found#201]
Hi 

I am using found-relay and have some routes defined as: 

```
<Route path="/" component={AppComponent} >
    <Route path="/dashboard" component={DashboardComponent}>
        <Route path="/modal/:id" component={SomeModal} />
    </Route>
</Route>

```
When I close the nested modal component, I want to load the parent component again so that I can fire the graphql query again for latest data. How can i do this with found @taion

**Comment by taion** [comment]
See https://github.com/relay-tools/found-relay/issues/101, or manually call the `retry` callback.

It's the same as if you were nesting `<QueryRenderer>` instances without any "real" changes to the variables.
