### ISSUE TITLE
Support Array, RegExp `path`

### ISSUE THREAD

**Issue by r1b** [4Catalyzer/found#206]
`path-to-regexp` supports Array, Regexp and string input [1]. `getCanonicalPattern` assumes that path will be a string [2], so it is not possible to use Array, RegExp `path` with found. Is this intended?

[1] https://github.com/pillarjs/path-to-regexp/blob/v1.7.0/index.js#L409
[2] https://github.com/4Catalyzer/found/blob/master/src/Matcher.js#L110

**Comment by taion** [comment]
um, i didn't know about this feature. would it be useful? i was sort of just going off the old react router API

**Comment by r1b** [comment]
The other types are nice if you want to say "match either *this* route or *that* one or ..." - tricky to do with a string (is it possible? - seems like you can only use a regexp for params).

**Comment by taion** [comment]
In the current scheme you could do something like:

```js
<Route {...props}>
  <Route path="<path1>" />
  <Route path="<path2>" />
  <Route path="<path3>" />
</Route>
```

Would this be sufficient?

**Comment by r1b** [comment]
yep that would work
