### ISSUE TITLE
IE11 error: Object doesn't support property or method 'hasOwnProperty'

### ISSUE THREAD

**Issue by shymkovayu** [4Catalyzer/found#207]
Hello!
I'm setting an app Reactjs 16.4.1 + React Realy + Found (via found-relay) + Redux. I'm using an example from the documentation for createConnectedRouter. Everything works fine, but in IE11 the app fails with an error 'Object doesn't support property or method 'hasOwnProperty'. By commenting out line by line of code I see that it fails on the line 'store.dispatch(FarceActions.init());'

```
export const store = createStore(
  combineReducers({
    ...rootReducer,
    found: foundReducer
  }),
  compose(
    createHistoryEnhancer({
      protocol: new BrowserProtocol(),
      middlewares: [queryMiddleware],
    }),
    createMatchEnhancer(
      new Matcher(routes, { matchStemRoutes: false }),
    ),
    applyMiddleware(thunk),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )
);

store.dispatch(FarceActions.init());

const ConnectedRouter = createConnectedRouter({
  render: createRender({
    renderReady: () => (
      <div style={{marginTop: 150}}>Debugging...</div>
    ),
    renderError: ({ error }) => (
      <div>
        {error.status === 404 ? 'Not found' : 'Error'}
      </div>
    ),
  }),
});

class App extends Component {
render(){
    return (
      <Provider store={store}>
        <ConnectedRouter resolver={resolver} />
      </Provider>
    )
  }
}
```

Could you please advise anything?

**Comment by taion** [comment]
I'm not sure this is coming from here. Do you have code that's trying to call `hasOwnProperty`? You may also be missing a polyfill to support old browsers.

**Comment by shymkovayu** [comment]
I've checked this already, I don't use it anywhere. Without this line, the component would render. But If I add it, it would fail. Event if I render a simple text line without router but with this line in the code.

**Comment by taion** [comment]
Can you trace to the exact line where the exception is getting thrown?

**Comment by shymkovayu** [comment]
<img width="978" alt="ie error" src="https://user-images.githubusercontent.com/5849953/45825278-2bef2300-bcf2-11e8-99d2-9b95365c8206.png">
This is from IE console.  In my code `store.dispatch(FarceActions.init());` throws an exception. I'm not sure how to trace it deeper.

**Comment by taion** [comment]
Can you include the full stack trace?

**Comment by shymkovayu** [comment]
<img width="965" alt="stack trace" src="https://user-images.githubusercontent.com/5849953/45826696-3bbc3680-bcf5-11e8-83ca-8d11a3f63234.png">
<img width="604" alt="error line" src="https://user-images.githubusercontent.com/5849953/45826699-3bbc3680-bcf5-11e8-82cf-5564eb3696bd.png">

Got it! I checked the mentioned in the stack trace line in the application.js and added a screenshot of the line that throws an exception.

**Comment by shymkovayu** [comment]
This seems to be an Object assign polyfill, isn't it?

**Comment by taion** [comment]
Yes, this looks like the Core-JS `Object.assign` polyfill. Can you provide your own instead?

**Comment by shymkovayu** [comment]
Do you know any common solution by any chance?

**Comment by taion** [comment]
I don't know the polyfills for old browsers.

The other thing that's happening is that this very likely isn't even due to the code here – dispatching the "init" action is what triggers all matching and routing.

I would set a breakpoint on exception there and look at exactly why this is getting hit. You can also look at https://github.com/ljharb/object.assign or pull in a ES5 shim or sham.

**Comment by shymkovayu** [comment]
@taion Thank you! For now, I removed object-assign-polyfill.
