### ISSUE TITLE
Top component in Route re-rendering twice on route load

### ISSUE THREAD

**Issue by bmcdaniel11** [4Catalyzer/found#211]
We have a Route component (`<TenantSwitcher>`) that lives at the top of our public routes() return that is getting rendered twice on a route load. 

Routes config:
```
const RootRouteComponent = (props: AppFrameProps) => (
  <TenantSwitcher>
    <GoogleAnalyticsProvider>
      <AppFrame {...props} />
    </GoogleAnalyticsProvider>
  </TenantSwitcher>
)

export default class extends RouteConfig {
  public routes() {
    return (
      <Route>
        <Route Component={RootRouteComponent}>
          {children}
        </Route>
      </Route>
    )
 }
```

I can even click the same route and it will render twice. Using `shouldComponentUpdate`, I can see it says `children` is dirty the first render and that `children, match` are different the second time.

This is the console for the rendering of the TenantSwitcher after clicking the link to the route I'm currently on:
 
<img width="1469" alt="members_-_archetype_com" src="https://user-images.githubusercontent.com/1737247/47879296-3c64e400-ddee-11e8-9984-edbad366be92.png">

Any idea why this is detecting two changes in the component?

**Comment by taion** [comment]
Do your nested components load data?

If they do, it will first render once with the children in "loading" state, then render again with the children in "loaded" state once they have their data.

**Comment by bmcdaniel11** [comment]
I found our issue. We have a state change that occurs when clicking on a route in the app drawer that ultimately causes an initial render to change the app drawer state before the Route Component causes a render when the route changes. Thank you for your response, I'll close out this issue.
