### ISSUE TITLE
v0.4.0-alpha.3 breaks @connect

### ISSUE THREAD

**Issue by NSLS** [4Catalyzer/found#229]
Hi!

We recently updated to the latest version of found to be able to use the latest `react-redux` version. Everything works fine until we try to use `@connect` in our component.

If `@connect` is used on a component passed to the `Route`, it produces the following error: 
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

We narrowed this down to be caused by the `context` prop being passed by `found`, which has the value of the `matchContext`. If the `context` prop is removed/renamed before the `@connect` call, everything works as expected.

In the `react-redux` changelog, there is a mention of this change, but I'm not sure as to how fix it properly.
![image](https://user-images.githubusercontent.com/8458382/51030331-c3c69480-15a1-11e9-8245-6c967aeb1cc1.png)

Maybe we should pass the `matchContext` with a different prop name to avoid any possible collisions?

**Comment by taion** [comment]
Ah, shoot. I wonder if it wouldn't be better to just skip passing in the match details to route components by default, and just make them use `withRouter` instead. Or else only pass in `match` and `router`, as we do right now in `withRouter`. Do you think that'd be too big of a breaking change?

**Comment by NSLS** [comment]
For me passing context in match and router seems like a good solution, since I only use context in `getData` functions and use `hocs` to pass some data from the context to the components.

So for our cases that wouldn't be a breaking change at all, but I can't speak for all users

**Comment by taion** [comment]
Do you use the props that automatically get passed in to route components at all? i.e. would it be a hassle to have to add `withRouter` for those, to get those props?

cc @jquense

**Comment by NSLS** [comment]
Yes, in some cases we use `match` and `router` props, but we have never used the `context` prop

**Comment by jquense** [comment]
I use the auto injected props, but i'd be fine with a symmetry between that and withRouter. e.g. `router` and `match`

**Comment by NSLS** [comment]
In my opinion moving the `context` prop into the `match` would solve this issue without too much hassle of upgrading the old code relying on `context`, if there is any.

**Comment by taion** [comment]
it's actually already on the `match` prop. we're just passing it in twice. will address

**Comment by taion** [comment]
okay, released in the latest alphas of found (and found-relay as appropriate)
