### ISSUE TITLE
[Alpha 0.4] Good practices to display components that use `Link` in docz and jest ?

### ISSUE THREAD

**Issue by ohardy** [4Catalyzer/found#238]
Hi,

Before the changes to react context and react redux, I used `getChildContext` and I could create a fake context so Link work without a true route configs etc.

But with alpha, its look more complicated.

Any simple base code to create a fake redux store/route configs so I can display/use my components that use Link from found in docz or jest for example ?

Thanks in advance

**Comment by taion** [comment]
related to https://github.com/4Catalyzer/found/issues/136

**Comment by taion** [comment]
@ohardy I added back the custom context in https://github.com/4Catalyzer/found/pull/307.
