### ISSUE TITLE
Anchor links

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#239]
Today I tried adding "anchor" links to a website and it triggers the routing process on click which it shouldn't do because "anchor" links are not supposed to navigate to any other location: they're just supposed to jump to a certain scroll position.
Are "anchor" links supported by this library?

**Comment by catamphetamine** [comment]
In my case clicking on an anchor link runs a routing process.
Is it supposed to do so?
Or is it not supposed to do so and it could be something related to my code hacking your library?

**Comment by taion** [comment]
if it's just an `<a>` rather than a `<Link>`?

**Comment by catamphetamine** [comment]
Yes

**Comment by taion** [comment]
How is routing getting triggered in the first place? We don't do anything inherently for anchors. Is a pop state event getting emitted somehow?

**Comment by catamphetamine** [comment]
> Is a pop state event getting emitted somehow?

Nothing is done, it's just an `<a/>` link.

If you don't know why it triggers in my case then I'll close this issue because it's not guaranteed to be a bug in your library.

**Comment by catamphetamine** [comment]
@taion 
So, I ran a quick test and I can confirm that it's a bug in this library.

Open the "basic" example directory.
https://github.com/4Catalyzer/found/blob/master/examples/basic/
Open `index.js`.

Add `<ul/>` items:

```js
        <ul>
          <LinkItem to="/foo">Foo</LinkItem>
          <LinkItem to="/bar">Bar (async)</LinkItem>
          <LinkItem to="/baz">Baz (redirects to Foo)</LinkItem>
          <LinkItem to="/qux">Qux (missing)</LinkItem>
          <LinkItem to="#anchor">Anchor (Link)</LinkItem>
          <a href="#anchor">Anchor (a)</a>
          <div id="anchor">Anchor</div>
        </ul>
```

Add `getData` to the parent route.

```js

  routeConfig: [
    {
      path: '/',
      Component: App,
      getData: () =>
        new Promise(resolve => {
          setTimeout(() => {
            console.log('Parent route data loaded')
            resolve()
          }, 1000);
        }),
      children: [
```

Run the modified example and click the links: both `<Link to="#anchor"/>` and `<a href="#anchor"/>` will result in a bug: routing will be performed resulting in parent route `getData` being called and `Parent route data loaded` being printed.

**Comment by taion** [comment]
Okay, I can see what's happening here. Thinking about this a bit more, I'm not sure that the behavior is incorrect. The current location actually _is_ changing, so to maintain invariants, it seems like it might make sense to re-run routing. Is this causing concrete problems?

**Comment by catamphetamine** [comment]
> The current location actually is changing

You mean navigating an achor link is a change of location?
It is for some old websites which didn't use HTML5 location API and insted used hash URLs for routing (even twitter was using those at some point).
I wouldn't consider navigating an anchor link a change of location, but if you think otherwise then you can close this issue.
My site is working with a workaround in `getData()` property on the `Route`: it compares next location with previous location and if an anchor link navigation is detected it returns.

https://github.com/catamphetamine/react-website/blob/2db0a5e18b0fc7bf06f657fbb122f65634f4795f/source/location.js#L75-L84

**Comment by taion** [comment]
I think your solution of handling it in `getData` is a good, general approach here. The `getData` API in principle allows different behavior based on hash, and I don't want to disable that for hash navigation that comes in as a `POP`.
