### ISSUE TITLE
useRouter() hook

### ISSUE THREAD

**Issue by Togrias** [4Catalyzer/found#242]
Hi,

Are there intentions to add functionality to inject router prop using React's hooks api?

instead of withRouter(MyComponent), we can use: 

const router = useRouter()

**Comment by taion** [comment]
Given the underlying use of React Redux for state management here, this may not be possible until https://github.com/reduxjs/react-redux/issues/1177 is addressed.

**Comment by Togrias** [comment]
A semi-elegant approach would be to switch out of redux to the context api.

**Comment by salvoravida** [comment]
6.0.1 to 6.2.1 - refactor - fix Performance
https://github.com/reduxjs/react-redux/pull/1201

test it now wih:
```
"react-redux": "npm:@salvoravida/react-redux@^6.2.1"
```

**Comment by taion** [comment]
Cool – I'll be happy to take a closer look once that lands. Thanks!

**Comment by salvoravida** [comment]
Hi guys it's official forked now
https://github.com/salvoravida/react-redux-fork

**Comment by taion** [comment]
Okay, I think we can action this. We'll just use our own context provider nested under the Redux context provider. `withRouter` injects the same data into all its components anyway, so we get the right semantics around re-render here with a hook.
