### ISSUE TITLE
React Context API

### ISSUE THREAD

**Issue by hisapy** [4Catalyzer/found#243]
Hi devs,

I'm trying to implement an authentication required route which would ask an `AuthContext` if the user is logged in and I think I found some limitations with how the Route component works:

```javascript
import React from "react";
import Route from "found/lib/Route";
import HttpError from "found/lib/HttpError";
import LoadingOverlay from "./LoadingOverlay";
import LinearProgress from "@material-ui/core/LinearProgress";
import { AuthContext } from "./auth-context";

export default class AuthRequiredRoute extends Route {
  render({ Component, props, error, match, resolving }) {
    // Couldn't useContext because hooks are only allowed in function components
    return (
      <AuthContext.Consumer>
        {({ loggedIn }) => {
          if (!loggedIn)
            throw new HttpError(401, "No JWT found in localStorage");

          // This error hasn't been caught by renderError yet, that's why we need to throw it
          if (resolving && error) {
            throw new HttpError(error.status, error);
          }

          if (Component && props) {
            return <Component {...props} />;
          }

          if (match.route.loadingOverlay) {
            return <LoadingOverlay />;
          }

          return <LinearProgress style={{ marginTop: "68px" }} id="cargando" />;
        }}
      </AuthContext.Consumer>
    );
  }
}
```

The problem with the above approach is 

```bash
react-dom.development.js:520 Warning: A context consumer was rendered with multiple children, or a child that isn't a function. A context consumer expects a single child that is a function. If you did pass a function, make sure there is no trailing or leading whitespace around it.
warningWithoutStack @ react-dom.development.js:520
updateContextConsumer @ react-dom.development.js:15661
beginWork @ react-dom.development.js:15881
performUnitOfWork @ react-dom.development.js:19745
workLoop @ react-dom.development.js:19786
renderRoot @ react-dom.development.js:19866
performWorkOnRoot @ react-dom.development.js:20811
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
enqueueSetState @ react-dom.development.js:11475
push.../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
_callee$ @ createBaseRouter.js:219
tryCatch @ runtime.js:63
invoke @ runtime.js:290
prototype.(anonymous function) @ runtime.js:116
step @ asyncToGenerator.js:21
(anonymous) @ asyncToGenerator.js:32
Promise.then (async)
step @ asyncToGenerator.js:31
(anonymous) @ asyncToGenerator.js:32
Promise.then (async)
step @ asyncToGenerator.js:31
(anonymous) @ asyncToGenerator.js:39
F @ _export.js:43
(anonymous) @ asyncToGenerator.js:18
resolveMatch @ createBaseRouter.js:302
componentDidMount @ createBaseRouter.js:118
commitLifeCycles @ react-dom.development.js:17636
commitAllLifeCycles @ react-dom.development.js:19141
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19360
completeRoot @ react-dom.development.js:20893
performWorkOnRoot @ react-dom.development.js:20816
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
scheduleRootUpdate @ react-dom.development.js:21061
updateContainerAtExpirationTime @ react-dom.development.js:21087
updateContainer @ react-dom.development.js:21155
push.../../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:21468
(anonymous) @ react-dom.development.js:21620
unbatchedUpdates @ react-dom.development.js:20938
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21616
render @ react-dom.development.js:21691
./src/index.js @ index.js:14
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
react-dom.development.js:520 Warning: A context consumer was rendered with multiple children, or a child that isn't a function. A context consumer expects a single child that is a function. If you did pass a function, make sure there is no trailing or leading whitespace around it.
warningWithoutStack @ react-dom.development.js:520
updateContextConsumer @ react-dom.development.js:15661
beginWork @ react-dom.development.js:15881
performUnitOfWork @ react-dom.development.js:19745
workLoop @ react-dom.development.js:19786
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
replayUnitOfWork @ react-dom.development.js:18976
renderRoot @ react-dom.development.js:19899
performWorkOnRoot @ react-dom.development.js:20811
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
enqueueSetState @ react-dom.development.js:11475
push.../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
_callee$ @ createBaseRouter.js:219
tryCatch @ runtime.js:63
invoke @ runtime.js:290
prototype.(anonymous function) @ runtime.js:116
step @ asyncToGenerator.js:21
(anonymous) @ asyncToGenerator.js:32
Promise.then (async)
step @ asyncToGenerator.js:31
(anonymous) @ asyncToGenerator.js:32
Promise.then (async)
step @ asyncToGenerator.js:31
(anonymous) @ asyncToGenerator.js:39
F @ _export.js:43
(anonymous) @ asyncToGenerator.js:18
resolveMatch @ createBaseRouter.js:302
componentDidMount @ createBaseRouter.js:118
commitLifeCycles @ react-dom.development.js:17636
commitAllLifeCycles @ react-dom.development.js:19141
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19360
completeRoot @ react-dom.development.js:20893
performWorkOnRoot @ react-dom.development.js:20816
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
scheduleRootUpdate @ react-dom.development.js:21061
updateContainerAtExpirationTime @ react-dom.development.js:21087
updateContainer @ react-dom.development.js:21155
push.../../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:21468
(anonymous) @ react-dom.development.js:21620
unbatchedUpdates @ react-dom.development.js:20938
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21616
render @ react-dom.development.js:21691
./src/index.js @ index.js:14
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
react-dom.development.js:15671 Uncaught TypeError: render is not a function
    at updateContextConsumer (react-dom.development.js:15671)
    at beginWork (react-dom.development.js:15881)
    at performUnitOfWork (react-dom.development.js:19745)
    at workLoop (react-dom.development.js:19786)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:18976)
    at renderRoot (react-dom.development.js:19899)
    at performWorkOnRoot (react-dom.development.js:20811)
```

if I'm not wrong, ReactDOM can't find a render method because the Route is not a React.Component; it's just a plain class. It's worth mentioning that I tried all sorts of simpler consumer functions with different formats, in case of leading or trailing space errors but all of them ended up with the same warning and errors.

The next thing I tried is to move the auth logic to a function component wrapper of `Component` in order to `useContext`:

```javascript
import React, { useContext } from "react";
import Route from "found/lib/Route";
import HttpError from "found/lib/HttpError";
import LoadingOverlay from "./LoadingOverlay";
import LinearProgress from "@material-ui/core/LinearProgress";
import { AuthContext } from "./auth-context";

const AuthWrapper = ({ Component, props, error, match, resolving }) => {
  const { loggedIn } = useContext(AuthContext);

  if (!loggedIn) throw new HttpError(401, "No JWT found in localStorage");

  // This error hasn't been caught by renderError yet, that's why we need to throw it
  if (resolving && error) {
    throw new HttpError(error.status, error);
  }

  if (Component && props) {
    return <Component {...props} />;
  }

  if (match.route.loadingOverlay) {
    return <LoadingOverlay />;
  }

  return <LinearProgress style={{ marginTop: "68px" }} id="cargando" />;
};

export default class AuthRequiredRoute extends Route {
  render(routeProps) {
    return <AuthWrapper {...routeProps} />;
  }
}
```

The problem with this approach is that the `HttpError` is not caught by the router's `renderError`, perhaps because as mentioned in React Error Boundaries docs:

> [As of React 16, errors that were not caught by any error boundary will result in unmounting of the whole React component tree.](https://reactjs.org/docs/error-boundaries.html#new-behavior-for-uncaught-errors)

Finally, I tried extending my AuthRequiredRoute from React.Component to add an error boundary but that wouldn't even match the current path.

1. Is there a way I can  _share some context_ with `Route`s dynamically without having to use a Redux router? 

2. Wouldn't it be better to make the `Route` a function component in order to use hooks and other React abilities?

**Comment by hisapy** [comment]
I tried a few other options, like adding an `ErrorBoundary`, without success, but which made think that perhaps a Route should have its own `ErrorBoundary` by default 

🤔

**Comment by taion** [comment]
Right, so the issue is that routes aren't actually components, and neither are their render functions. Routes are just there for configuration, while render functions are just normal functions that return React elements in some sense.

If you need to access some global context in your `render` functions, right now the best approach is to pass it in via `matchContext` per https://github.com/4Catalyzer/found#data-or-getdata. It will then be available in the same way in the `render` method.

**Comment by hisapy** [comment]
Thanks but I was hoping to handle this more _globally_ ... in the meantime I'll just read localStorage in the my `AuthRequiredRoute`  ... but leaving a TODO to see what can be done in the future

**Comment by taion** [comment]
The match context feature is the way to get global context into routing handling. To avoid oddness around pending state handling, we're handling the top-level render resolution outside of React rendering. And unlike e.g. localStorage, `matchContext` will work in an SSR context too.

**Comment by hisapy** [comment]
🤔 

I'm not sure I understand yet but anyway, I wonder how that will work with found-relay

**Comment by hisapy** [comment]
Hi again, 

I tried

```jsx
<FarceRouter
  matchContext={{ loggedIn }}
   resolver={new Resolver(getRelayEnvironment(accessToken))}
/>
```

and added `getData` to `AuthRequiredRoute` 

```javascript
getData({ 
  console.log(context);
  if (!context.loggedIn) throw new HttpError(401, "No access token");
}
```

but it's not being called. 

And I still don't understand what's like
> _handling the top-level render resolution outside of React rendering

**Comment by taion** [comment]
If you're using Found Relay, `getData` doesn't get called. You can still read the `context` in either `render` or `getQuery`, though.

**Comment by hisapy** [comment]
Thanks again @taion ... fortunately it's a piece of cake ... I accessed it via `match.context.loggedIn` in my render.

I hope I don't have to deal with _handling the top-level render resolution outside of React rendering_ because that's the part I can't understand yet 😅

**Comment by taion** [comment]
You don't need to deal with that – that's what the router handles right now.

**Comment by mbaquerizo** [comment]
Hey @taion,

Didn't want to create a new issue for this since it has been answered numerous times already. I'm trying to figure out a solution to handling authorization per route.

I am seeing you refer to `matchContext` here and other issues brought up regarding this, and I'm just not seeing/understanding what `matchContext` is and how it will help me. Let me describe my situation...

I am upgrading an application that used relay classic and react router (v2/3), to relay modern and found-relay. We are using SSR as well. Previously we used the `onEnter` prop on react-router's Route:

```
<Route
  path="account"
  onEnter={(nextState, replace, callback) => requireAuth(nextState, replace, callback, req, RoleTypes.USER)}
>
```
The `requireAuth` sends a request to our backend with the userToken cookie to check against our db which returns a 201 status if the user is authenticated, along with an object containing the user's role.
If a 201 is returned we check the user's role against the role passed in to `requireAuth` and either `callback()` or `replace()` if the user doesn't have the required role.

I'm not sure if this approach is the best for found-relay and it seems like it wouldn't work anyway. I tried putting similar logic in `render` (except returned true/false based on backend response):
```
export default class AuthorizedRoute extends Route {
  constructor(props){
    super(props);

    this.request = props.request;
    this.requiredRole = props.requiredRole;
  }

  render({Component, props}){
    if(!props){
      return <div>Loading...</div>;
    }
    requireAuth(this.requiredRole, this.request).then((isAuthorized) => {
       if(isAuthorized() === true){
           return <Component {...props} />
       } else {
           throw new RedirectException('/login');
       }
    });
  }
}
```
This results in `Uncaught (in promise) RedirectException {location: "/login"}`.

So given that I have to get data from our backend, where should that request happen, and where would `matchContext` come in if applicable?

**Comment by hisapy** [comment]
Hi @mbaquerizo 

Do you have `renderError` configured in the router?.

Also, you might want to consider returning an error to just render a Login component instead of having a "/login" path. Not having to deal with a "/login" path and just render a `Login` component whenever an auth error is detected simplified lots of stuff for me.

Here is my router in case you find it useful

```javascript
const FarceRouter = createFarceRouter({
    historyProtocol: new BrowserProtocol(),
    historyMiddlewares: [queryMiddleware],
    routeConfig: routeConfig,

    render: createRender({
      renderError({ error, router, location }) {
        if (process.env.NODE_ENV !== "test") {
          // eslint-disable-next-line no-console
          console.error(error);
        }

        switch (error.status) {
          case 401:
            return <Login router={router} location={location} />;
          case 404:
            return <h1>Página no encontrada o en construcción</h1>;
          default:
            return <h1>Ha ocurrido un error. Intente recargar la página</h1>;
        }
      }
    })
  });
```

**Comment by taion** [comment]
@mbaquerizo on your auth thing – is the idea that you're hitting an API that's _separate_ from your GraphQL API to determine user authed state? as opposed to the auth check being something inside graphql

**Comment by mbaquerizo** [comment]
That's correct. It was built as a separate API endpoint (/auth/validate)

**Comment by hisapy** [comment]
I just noticed that in my previous post I didn't answered the question 

>So given that I have to get data from our backend, where should that request happen, and where would `matchContext` come in if applicable?

In my case, I use `matchContext` in a root `App` stateful component that 

```javascript
    return (
      <AuthContext.Provider value={{ login, logout, projectSlug }}>
        <FarceRouter
          matchContext={{ loggedIn: !!accessToken }}
          resolver={new Resolver(getRelayEnvironment(accessToken))}
        />
      </AuthContext.Provider>
    );
```

and in my `AuthRequiredRoute` I read read the context from match.context:

```javascript
if (!match.context.loggedIn) throw new HttpError(401, "No access token");
```

the error is then handled by the render error configured in the router. The `AuthContext` is fed with `login` and `logout` functions that can be called from components such as `Login` and `LogoutLink`.

I think I have a similar setup as yours but in my case, Authentication is done in a separate API endpoint but Authorization is done in the backend used behind our GraphQL layer, so if someone is trying to query fields without the required role, then an error is returned.

In your setup:

1. you `requireAuth` **after** you got the data from GraphQL 
2 It seems that you're missing the return value for _when there are props_. According to [the docs](https://github.com/4Catalyzer/found/tree/next#render) this should be a react element, undefined or null ...

Perhaps, you might want to `requireAuth` in your RelayNetworkLayer or query your user roles from GraphQL

**Comment by mbaquerizo** [comment]
> In my case, I use `matchContext` in a root `App` stateful component that renders:
> 
> ```js
>     return (
>       <AuthContext.Provider value={{ login, logout, projectSlug }}>
>         <FarceRouter
>           matchContext={{ loggedIn: !!accessToken }}
>           resolver={new Resolver(getRelayEnvironment(accessToken))}
>         />
>       </AuthContext.Provider>
>     );
> ```
> 
> and in my `AuthRequiredRoute` I read read the context from match.context:

In your case, before you return, where is `accessToken` coming from?

> 2\. It seems that you're missing the return value of `render` for _when there are props_. According to [the docs](https://github.com/4Catalyzer/found/tree/next#render) this should be a react element, undefined or null ...

I realized the code I posted above was bad code. I actually tried a few things but realized since the `requireAuth` is returning a promise, that promise wasn't being resolved by the time `render` happened

I am thinking it would be easiest to do something like

```js
render({Component, props}){
  if(!props){
    return <div>Loading...</div>
  }
  if(props.Viewer.Role !== this.requiredRole){
    return <Login /> // or redirect or throw 401 error 
  } else return <Component />
}
```
Is this a good approach?

**Comment by hisapy** [comment]
> In your case, before you return, where is `accessToken` coming from?

Is coming from 

```javascript
  const App = () => {
    const [accessToken, setAccessToken] = useState(
      localStorage.getItem("accessToken")
    );
    // other stuff here
    // render here
  }
```

We're going to stop using localStorage though, but the base idea would still be the same.

> Is this a good approach? Edit: Or is it better to use matchContext in some way (which I am still not really understanding)?

There is no better or worse. I think there are just different _strategies_. In my particular case, we don't query viewer, nor authorize at UI route level. We just let the server handle authorization and return related errors that we handle in `renderError`. 

That say, I don't see why you'd need to use `matchContext` if you're querying for the viewer in each route. By the way, you'd have to make sure `props.viewer` before asking for its `.role` 😉 

Overall, perhaps it's time for someone to write a book or a great _(un)official_ tutorial about how these technologies work together.

**Comment by taion** [comment]
Yeah, so that exact pattern isn't quite supported with Found Relay – `render` needs to return synchronously and can't return a promise.

So per @hisapy's example above, we do something like have a wrapping component that handles auth, which then renders the router, and does something like `
matchContext={{ loggedIn: !!accessToken }}` or the equivalent.

Then the route `render` methods can check `context.loggedIn` and throw the `RedirectException` if needed.
