### ISSUE TITLE
ConnectedRouter.componentDidUpdate Warning: Scheduled a cascading update

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#345]
When debugging "Performance" using Chrome DevTools I can see the warning:

> ConnectedRouter.componentDidUpdate Warning: Scheduled a cascading update

Which means that React has to re-render something because `<ConnectedRouter/>`'s `componentDidUpdate()` calls `this.setState()`.

`<ConnectedRouter/>` is created here:

https://github.com/4Catalyzer/found/blob/v0.3-dev/src/createConnectedRouter.js

It inherits from "base router":

https://github.com/4Catalyzer/found/blob/v0.3-dev/src/createBaseRouter.js

Which says:

```js
    // We use componentDidMount and componentDidUpdate to resolve the match if
    // needed because element resolution is asynchronous anyway, and this lets
    // us not worry about setState not being available in the constructor, or
    // about having to pass around nextProps.
```

I don't know if this is a bug or not.
Maybe it's not a bug: there are no similar issues created in this repo.

**Comment by catamphetamine** [comment]
I don't know if this is a bug or not.
Maybe it's not a bug but there aren't similar issues created in this repo.

**Comment by catamphetamine** [comment]
Actually, this doesn't seem like an issue to me.

**Comment by taion** [comment]
Yeah, it doesn't really matter because it's async regardless... it's not immediately re-rendering, mostly.
