### ISSUE TITLE
store.dispatch(FarceActions.push('/new/path')); doesn't re-render page

### ISSUE THREAD

**Issue by ilyhryh** [4Catalyzer/found#369]
I use found + farce + found-relay + redux.

```js
onClick={() => store.dispatch(FarceActions.push(`/${item._id}`))}
```

It changes URL and pushes new entry to store, but doesn't re-render page. I want the same behavior as `<Link />` component, but without using it. 

```html
<tr onClick={() => store.dispatch(FarceActions.push(`/${item._id}`))} >
  <td>something</td>
  <td>something</td>
  ...
  <td>something</td>
</tr>
```

**Comment by taion** [comment]
How are you getting access to `store` there, exactly? Shouldn't you just be getting `dispatch` passed down from `connect()`?

Check the instructions in https://github.com/4Catalyzer/found#createconnectedrouter to ensure you have the router and the store properly connected.

**Comment by Victorien-Tardif** [comment]
Hi, I used to dispatch FarceActions from sagas (https://github.com/redux-saga/redux-saga) and since I moved from 0.3.11 to 0.4.2 it does not work anymore. I can see the action being dispatched in redux-devtools but the redirection is not performed :/

**Comment by taion** [comment]
Closing for staleness

**Comment by damassi** [comment]
Without directly using redux / store, I've noticed something similar happening after a hot reload -- router.push('/some/path') will update the url, but the next page won't render.

**Comment by taion** [comment]
Weird – they should do the same thing. Which hot reloader are you using?

**Comment by damassi** [comment]
Yeah, digging into the code I saw that. Its super odd I agree. It could very well be somethingg with our app setup. Using react-hot-middleware.
