### ISSUE TITLE
Add hash location support

### ISSUE THREAD

**Issue by amorino** [4Catalyzer/found#37]
Which is the minimum supported browsers? Same as React?

**Comment by taion** [comment]
I've updated the issue to reflect what's missing. Currently the only supported navigation scheme is the HTML5 History API, so IE >= 10. There's also a caveat on hash-only changes in certain versions of IE: https://github.com/4Catalyzer/farce/blob/v0.1.0/src/BrowserProtocol.js#L49-L50.

**Comment by taion** [comment]
Track this on https://github.com/4Catalyzer/farce/issues/21 instead, since the actual issue is there
