### ISSUE TITLE
Add server rendering support

### ISSUE THREAD

**Issue by taion** [4Catalyzer/found#38]
To do this, we'd need to consume the iterable from `resolveElements` to the end, then render with that result. We'd have to do the same thing on the client side to set `initialRenderArgs` due to the async nature of element resolution as well.

**Comment by taion** [comment]
This probably also requires some sort of `StaticProtocol` or `ServerProtocol` in Farce, given our dependence on Farce APIs for generating e.g. `<Link>` `href`s.

**Comment by steida** [comment]
I really need the server-side rendering for Este. Should I start to implement it or wait for API changes?

**Comment by taion** [comment]
It's coming – do you have a good boilerplate for setting up a very basic SSR example?

**Comment by steida** [comment]
I would use https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#integrating-with-a-node-backend

**Comment by taion** [comment]
That's not quite right – it's for an API server, not for SSR.

**Comment by steida** [comment]
You can grab the Este and try to replace it's server side logic https://github.com/este/este/blob/master/src/server/frontend/render.js

**Comment by steida** [comment]
Btw, this is so awesome talk https://vimeo.com/166790294 
![screen shot 2016-11-18 at 18 42 50](https://cloud.githubusercontent.com/assets/66249/20440092/d3d6b67c-adbe-11e6-9e44-5e10ac550546.png)

**Comment by LorbusChris** [comment]
I personally found [react-universally](https://github.com/ctrlplusb/react-universally) very comfortable to work with. @ctrlplusb is also open to new branch ideas. 

I am using Found in [this](https://github.com/LorbusChris/react-universally) WIP repo. Once there is an SSR API, a solution for rendering of the code-split-state's chunks can surely be realised (like in [code-split-component](https://github.com/ctrlplusb/code-split-component), which comes with a webpack plugin. Found however already takes care of the client side things that it does).

**Comment by LorbusChris** [comment]
I have created a [found branch](https://github.com/LorbusChris/react-universally/tree/found) on my fork.

@taion maybe [this file](https://github.com/LorbusChris/react-universally/blob/found/src/universalMiddleware/index.js) is a good starting point. CSR works fine, but SSR is currently disabled. Great work you're doing here, btw!

To get an idea of how I implemented found in the project, the [comparison](https://github.com/ctrlplusb/react-universally/compare/master...LorbusChris:found) between my found branch and master may be helpful.

**Comment by taion** [comment]
Take a look at https://github.com/4Catalyzer/found/pull/56. I haven't added docs yet, but the example shows the basic API (more details in PR).

**Comment by rojobuffalo** [comment]
Correct me if I'm wrong, but in the example isn't the render on the server-side operating without webpack? So that means no assets (styles and images) can be composed within the react app? For your projects do you deal with assets in a different way?

**Comment by taion** [comment]
You can make a webpack bundle targeting Node, and it will work just fine. Same with anything else. I just opted for making the example simpler.

**Comment by rojobuffalo** [comment]
I think you're right. It just got really hairy trying to webpack the server which webpacks the client. Running those compiles separately and still having everything shake out was getting really difficult and I had to abandon it.
