### ISSUE TITLE
parent component not rendered anymore?

### ISSUE THREAD

**Issue by Victorien-Tardif** [4Catalyzer/found#431]
I have some trouble updating from 0.3.11 to 0.4.2 (some routes are just not found anymore) and I noticed that taking this example route config:

```
const routeConfig = [
  {
    path: '/',
    Component: AppPage,
    children: [
      {
        Component: MainPage,
      },
      {
        path: 'foo',
        Component: FooPage,
        children: [
          {
            path: 'bar',
            Component: BarPage,
          },
        ],
      },
    ],
  },
];
```
the route /foo will never be matched and the component FooPage never rendered.... I can only manage to display BarPage on /foo/bar.

Am I the only one?

**Comment by Victorien-Tardif** [comment]
adding `{ path: ''`} as first child seems to do the trick....:
```
export const routeConfig = [
  {
    path: '/',
    Component: AppPage,
    children: [
      {
        Component: MainPage,
      },
      {
        path: 'foo',
        Component: FooPage,
        children: [
          {
            path: '',
          },
          {
            path: 'bar',
            Component: BarPage,
          },
        ],
      },
    ],
  },
];
```

**Comment by taion** [comment]
Yup, you'll want to add a child like `{}` under the route you want to match. The `path: ''` is not necessary.

We changed this in https://github.com/4Catalyzer/found/pull/217, as previously it wasn't really possible to get `/foo` _not_ to match, in the event that there wasn't supposed to be a route there.

So now "index routes" must explicitly be specified, and are no longer assumed to be there, to give you a bit more control.

**Comment by Victorien-Tardif** [comment]
Ok thanks!
