### ISSUE TITLE
managing URL query parameters

### ISSUE THREAD

**Issue by DaniloOliveira28** [4Catalyzer/found#445]
Hi!

I am trying to add the useQueryParams package to handle url query params, however I am not understanding what part I need to customize to make it works. 
https://github.com/pbeshai/use-query-params/

I need to pass the history and location to useQueryParams. How Can I do that?
https://github.com/pbeshai/use-query-params/blob/e40ecc2309006ee05dc2f19b69cae6399d0f9ee2/src/QueryParamProvider.tsx#L169

We are using the found relay package as well.

Can you give guidance how I can add the useQueryParams in found package?

**Comment by taion** [comment]
I'm not sure they can necessarily integrate without some additional shim.

I will say that the underlying navigation component, Farce, has fairly robust support for managing queries itself. You can use `createFarceRouter` to customize the Farce middlewares, and `createQueryMiddleware` to customize how you stringify and parse queries from the string: https://github.com/4Catalyzer/farce#querymiddleware-and-createquerymiddleware

Given that, using just the components here, you can access the current parsed query as `location.query` with something like `const { match: { location } } = useRouter()`, and get access to anything you want on the query that way.
