### ISSUE TITLE
Some props error from example

### ISSUE THREAD

**Issue by beckend** [4Catalyzer/found#48]
```js
// createRoutes.js
import { Page as AppPage } from './index';
import { Page as MainPage } from 'web/mobile/Main';

export const createRoutes = () => {
  const routeConfig = [
    {
      path: '/',
      Component: AppPage,
      children: [
        {
          Component: MainPage,
        },
      ],
    },
  ];

  return {
    routeConfig,
  };
};
```

```js
// main.jsx using routeConfig
...
const ConnectedRouter = createConnectedRouter({
  routeConfig,
  matcher,

  render: createRender({
    renderError: ({ error }: { error: any }) => (
      <div>
        {error.status === 404 ? 'Not found' : 'Error'}
      </div>
    ),
  }),
});

const BootstrapComponent = (
  <Provider store={ store }>
    <ConnectedRouter resolveElements={ resolveElements } />
  </Provider>
);

render(
  BootstrapComponent,
  document.getElementById('__ROOT__')
);
```

Result:

![screenshot from 2016-11-23 21-41-31](https://cloud.githubusercontent.com/assets/6056334/20578088/cd5f62b6-b1c5-11e6-90b1-d0c45af60e24.png)

**Comment by taion** [comment]
How are you setting up your store?

**Comment by beckend** [comment]
It's quite some code, but I have done console logs on the store, it has the found reducer and was populated when I ran the action when I created the store.

**Comment by beckend** [comment]
```js
// compose redux
  const matcher = new Matcher(routeConfig);
  const enhancer = compose(
    // found router
    createHistoryEnhancer({
      protocol: new BrowserProtocol(),
      middlewares: [queryMiddleware],
    }),
    createMatchEnhancer(matcher),
    ...otherComposedStuff
  );
```

Resulting reducer after dispatched action:
```js
"{"match":{"location":{"action":"POP","pathname":"/","search":"","hash":"","index":0,"delta":0,"query":{}},"routeIndices":[0,0],"routeParams":[{},{}],"params":{}},"resolvedMatch":{"location":{"action":"POP","pathname":"/","search":"","hash":"","index":0,"delta":0,"query":{}},"routeIndices":[0,0],"routeParams":[{},{}],"params":{}}}"
```

**Comment by taion** [comment]
It's possible you're using a store enhancer that's not properly forwarding through other properties on the store.

`createConnectedRouter` requires that `store.found` and `store.farce` have the relevant properties that implement the actual routing methods. Ensure that those are available.

**Comment by beckend** [comment]
Ok here is my store:
![screen shot 2016-11-24 at 09 19 46](https://cloud.githubusercontent.com/assets/6056334/20591109/38ac21e2-b227-11e6-8cf7-8015633bb1e6.png)

**Comment by beckend** [comment]
Here is a react debug of the Component:
![screenshot from 2016-11-24 19-30-44](https://cloud.githubusercontent.com/assets/6056334/20607911/aa46765e-b27c-11e6-9d4a-0962ddf1c236.png)

**Comment by beckend** [comment]
I have done some research on the codebase:
[Function addExtraProps](https://github.com/4Catalyzer/found/blob/master/src/createConnectedRouter.js#L45) is never called in the entire codebase.

**Comment by beckend** [comment]
I solved it by doing:
```js
const BootstrapComponent = (
  <Provider store={store}>
    <ConnectedRouter {...store.found} {...store.farce} resolveElements={resolveElements} />
  </Provider>
);
```

**Comment by taion** [comment]
It's a React Redux thing. Most likely you're somehow using the wrong version of React Redux... somehow?

**Comment by beckend** [comment]
package.json says redux 3.6.0

**Comment by beckend** [comment]
and react-redux 4.4.6

**Comment by beckend** [comment]
Did a search on entire codebase on react-redux for addExtraProps, nothing found.

**Comment by beckend** [comment]
Did the same search for redux repo, nothing found.

**Comment by taion** [comment]
You can see clearly that the `package.json` here does _not_ say that: https://github.com/4Catalyzer/found/blob/v0.1.3/package.json#L39

**Comment by beckend** [comment]
Yea thanks for that, all I did was `npm -S install found`. Forcing the package `npm -S i react-redux@next` solved it.
I don't know if this has to do with npm@4 or not, regardless I spent enough time on debugging this...
