### ISSUE TITLE
...is this a bad idea?

### ISSUE THREAD

**Issue by Thomazella** [4Catalyzer/found#615]
Howdy! I believe I have a test setup problem/setup problem, I fixed it by changing the `getFarceResult` function below:

```ts
const getFaceResultWithBrowserProtocol = async (
  args: GetFarceResultArgs,
): Promise<FarceElementResult | FarceRedirectResult> => {
  const {
    historyMiddlewares,
    historyOptions,
    routeConfig,
    matchContext,
    resolver = defaultResolver,
    renderPending,
    renderReady,
    renderError,
    render = createRender({
      renderPending,
      renderReady,
      renderError,
    }),
  } = args;
  const store = createFarceStore({
    historyProtocol: new BrowserProtocol(), // 👈🏻👈🏻👈🏻👈🏻👈🏻
    historyMiddlewares,
    historyOptions,
    routeConfig,
  });
  let renderArgs;

  try {
    renderArgs = await getStoreRenderArgs({
      store,
      matchContext,
      resolver,
    });
  } catch (e) {
    if (e.isFoundRedirectException) {
      return {
        redirect: {
          url: store.farce.createHref(e.location),
        },
      };
    }
    throw e;
  } finally {
    store.dispatch(FarceActions.dispose());
  }

  return {
    status: renderArgs.error ? renderArgs.error.status : 200,
    element: <RouterProvider renderArgs={renderArgs}>{render(renderArgs)}</RouterProvider>,
  };
};
```

I'm testing my relay app using relay modern and SSR, and I was running into a crash after my mutation was executed. Crasing file: `node_modules/farce/lib/createHistoryMiddleware.js` Error: `protocol.transition is not a function`. After some debugging I came to the conclusion it was because `getFarceResult` uses ServerProtocol inside which does not have some prototypes the middleware was expecting. At this point I had 2 options:
- Try to fix the crash by looking at the lib code and putting something together, which I did and it worked (the function above)
- Mock stuff to avoid the crash, perhaps using `jest.spyOn`.

While my problem is fixed, for now, I'd like some input, if possible, from lib authors and maintainers who will be more familiar with the internals than me.

My test: https://gist.github.com/Thomazella/e0cbac57f9df4186dbe91d68c8d345cb
mountWithRouter helper: https://gist.github.com/Thomazella/00947a4d4d9b994b22956c694f2a176f
What component looks like. Actually it just calls this code after the mutation resolves:
```
          const { r } = props.match.location.query;
          props.match.router.push(r || `/`);
```

**Comment by Thomazella** [comment]
PS: Thanks a ton for any input on this ppl, I understand it's a lot to ask for, and a lot of code.

**Comment by taion** [comment]
Have you seen the code in the tests here to run tests with navigation? https://github.com/4Catalyzer/found/blob/10e4be184384cdfa111c7308955dbe25c46cbf8a/test/redirect.test.js#L13-L51

If you're actually navigating around, I think it'd make more sense to just mount a router using `MemoryProtocol` (or `BrowserProtocol`), then instrumenting the resolver as in the example above to wait for navigation to complete.

**Comment by Thomazella** [comment]
thanks :D
