### ISSUE TITLE
`<Redirect/>` event doesn't provide `routeIndices` on "Back" navigation

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#632]
`<Redirect/>` event doesn't seem to provide `routeIndices` when a user clicks "Back" browser button after being redirected.

In routes we have this:

```js
<Route
  path="pathways"
  Component={Pathways} />

<Redirect
  from="transfer"
  to="pathways" />
```

Upon navigating to `/transfer` it redirects to `/pathways` and **after clicking the "Back" browser button** I can see the following Redux events being emitted:

```js
{
  type: "@@found/UPDATE_MATCH",
  payload: {
    location: {action: "POP", pathname: "/transfer", search: "", hash: "", key: undefined, …}, 
    routeIndices: [0, 12], 
    ...
  }
}
```

```js
{
  type: "@@found/UPDATE_MATCH",
  payload: {
    location: {action: "POP", pathname: "/transfer", search: "", hash: "", key: undefined, …}, 
    routeIndices: [0, 12], 
    ...
  }
}
```

```js
{
  type: "@@found/UPDATE_MATCH",
  payload: {
    location: {pathname: "pathways", search: "", hash: "", action: "REPLACE", key: "6py5kk:0", …}, 
    ...
  }
}
```

```js
{
  type: "@@found/RESOLVE_MATCH",
  payload: {
    location: {pathname: "pathways", search: "", hash: "", action: "REPLACE", key: "6py5kk:0", …}, 
    ...
  }
}
```

The last `RESOLVE_MATCH` event doesn't have `routeIndices`.
Is it by design? Can `routeIndices` be obtained somehow for such redirect event?
My application uses `routeIndices` to get Route `Component`s from which `<meta/>` and `<title/>` are read and applied on the page. Also, a `Component` might have `.loadData()` static function, which is also run in `RESOLVE_MATCH` normally.

**Comment by taion** [comment]
Are you sure there's no `routeIndices`? I'm not sure how that could happen. The code in `createMatchEnhancer` spreads in the result of `matcher.match` into the payload for `UPDATE_MATCH` as long as _some_ route matches, per https://github.com/4Catalyzer/found/blob/e922c71a8b2a979320cd3d79de49be139c397f5a/src/createMatchEnhancer.js#L18.

Is it possible your logging is omitting something?

FWIW you'd probably find it easier to set meta/title stuff from route `render` methods. You have access to the full list of matched routes via `match.routes`, and you can inject things as needed via match context.

**Comment by catamphetamine** [comment]
@taion I've updated to `found@0.4.9` and still don't see `routeIndices` in `RESOLVE_MATCH` when clicking "Back" browser button on a redirect-to page (that theoretically would take the user to redirect-from page).
See the screenshot:

![image](https://user-images.githubusercontent.com/477167/69680731-d2844000-10bc-11ea-9175-36d328a99d57.png)

If you're interested you can observe the issue on this website:
http://acadeum-public-site-develop.s3-website-us-east-1.amazonaws.com/transfer

The link redirects from `/transfer` to `/pathways` on client side.
Then click any link in the menu (doesn't matter).
Then click "Back" browser button, open the console, clear it, and click "Back" browser button again: you'll see the console output shown on the screenshot.
I don't think I'm myself emitting this Redux action in my code: I did a "Find in Files" search and it didn't return any results.

**Comment by taion** [comment]
Shouldn't it be `/pathways`, not `pathways`?

**Comment by catamphetamine** [comment]
@taion , hmm, indeed: it used `/transfer` for the "correct" Redux action and `pathways` for the "incorrect" one.
I'll try changing it to `/pathways` in the route config and will report back.

Update: maan, it worked.
Thanks!
Perhaps the router could throw in the case of a missing leading slash or something.
Closing.
