### ISSUE TITLE
`renderArgs.elements` is empty when navigating to the same route

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#639]
In my app I sometimes have links from a route to the same route, but with different `pathname`.
Those are forum `Thread` pages: one thread could link to another thread.
In some previous versions `renderArgs.elements` seemed to be always present, so my workaround of doing:

```js
renderArgs.elements[renderArgs.elements.length - 1] = 
  React.cloneElement(renderArgs.elements[renderArgs.elements.length - 1], {
    key: renderArgs.location.pathname
  })
```

seemed to work.
It doesn't seem to work anymore, because when navigating from a thread to another thread `renderArgs.elements` seems to be `undefined`.
Could it be the case?
If yes, perhaps could you propose any potential workaround for this case?
My current workaround is creating a wrapper over `Thread` page component that would set a `key` on the wrapped `Thread` page — seems to work.

```js
export default function ThreadPageWrapper() {
  const board = useSelector(({ chan }) => chan.board)
  const thread = useSelector(({ chan }) => chan.thread)
  return <ThreadPage key={`${board.id}/${thread.id}`}/>
}

ThreadPageWrapper.meta = ThreadPage.meta
ThreadPageWrapper.load = ThreadPage.load
```

**Comment by taion** [comment]
I'm not aware of any changes here. Where are you trying to access `renderArgs.elements`? If `elements` were somehow not present at the top-level render bit, then I'd expect rendering to completely fail: https://github.com/4Catalyzer/found/blob/2b439b6f509c932f3a100f1deffed667b6dd55a6/src/createRender.js#L21-L25

That said, if your goal is to do this for your page, could you just do this in the `render` method on the route itself? Something like:

```js
<Route
  // ...
  render=({ Component, data, match }) => (
    (Component && data) ?
      <Component key={match.location.key} data={data} />  :
      <LoadingIndicator />
  )}
/>
```

or something along those lines?

**Comment by catamphetamine** [comment]
> Where are you trying to access `renderArgs.elements`?

In `createConnectedRouter.render`. See the code:
https://github.com/catamphetamine/react-pages/blob/master/source/router/client.js

> That said, if your goal is to do this for your page, could you just do this in the render method on the route itself? Something like:

Well, that's what my code linked above was doing, I assumed: it was supposed to intercept the `render()` of each and every route and add the `key`.
Or would you have a better idea of a place where this "hook" could be added (once, not for every route).

**Comment by taion** [comment]
Ah, okay – in that place, `elements` is not necessarily defined. Reference https://github.com/4Catalyzer/found/blob/2b439b6f509c932f3a100f1deffed667b6dd55a6/src/createRender.js#L13-L34 – we could be in the "pending" or "error" branch. I'd just wrap your logic above in an `if` block.

If you were using `createRender` more-or-less directly to generate the `render` function to pass into one of the routers, then you could also just put the logic in `renderFetched` there, but it looks like you have enough custom logic that it'd probably be easier just to use the `if (renderArgs.elements)` in here.

**Comment by catamphetamine** [comment]
@taion Actually, your comment helped me understand the issue I was having.
Turned out it wasn't in the router library.
Instead, it's in the way the app is engineered.
So, there's a `Thread` page that fetches some `data` that is then stored in Redux state under `state.thread.data`.
When a navigation happens from one thread to another thread, `getData()` is run which fetches `data` for the next thread, but the application still renders the previous thread.
If a `Thread` page uses some state (`useState()`) then it creates a short period of inconsistency.
In my case, there was a state variable `fromIndex` controlling which posts are being displayed.
So if a previous thread had 200 posts with `fromIndex` being 100, and then the next thread is being loaded having 50 posts then it threw an "index out of bounds" error when accessing `state.thread.data[fromIndex]`.
So looks like this issue is not related to the router library in any way: it actually looks like a Redux architecture issue.
The way Redux apps are constructed, simply overriding state, instead of having something like Relay managing a separate state for each object id, managing caching, clearing cache (RAM), etc.
Just remounting a page component every time `location.pathname` changes doesn't solve this type of cases. In fact, it introduces an unneeded re-mount of the page component with the correct solution applied: first the page is re-mounted when object id changes, and then it's re-mounted the second time when `location.pathname` changes after `getData()` has finished.
I guess I'll remove the `key={location.pathname}` workaround then... Instead, I'll just be using `<Component key={object.id}/>` for every component having a URL parameter `:param` in its `path`. Maybe I'll even make it like this: at startup the app will analyze the `path` of every route, extract all named parameters from it, and then demand the developer supply some `Component.params = (state) => ({ threadId: state.thread.id })` object that will be converted into a key via `JSON.stringify(Component.params(state))` and this way re-mounting of page components will work correctly with Redux.

**Comment by taion** [comment]
A couple of thoughts:
- Yeah, with app-level state, Redux makes it a little too easy to have a single reducer that has data for multiple entities. Relay does do caching/RAM management, but in practice, unless you're targeting very low-end devices, you don't get much out of that logic. Our production Relay site has all of the GC stuff disabled.
- What are you trying to display while things are in the process of updating? I guess the way I pictured this working was that `getData` (or the equivalent) would return a promise, and the route would display some sort of loading indicator and unmount the actual component that renders the fetched data while data were being fetched.

**Comment by catamphetamine** [comment]
@taion 

> What are you trying to display while things are in the process of updating? I guess the way I pictured this working was that `getData` (or the equivalent) would return a promise, and the route would display some sort of loading indicator and unmount the actual component that renders the fetched data while data were being fetched.

The app always displays the "previous" screen while loading the next one, with a loading indicator on top.
The "prevoius" page isn't unmounted, and that creates this window of inconsistency.
I figured it requires some way to "freeze" updates to the "previous" page component while the "next" one is being loaded.
If I just wrapped some kind of `<Freezer/>` around every page that wouldn't work, because the `<Freezer/>` would simply return `<Page/>`, and `<Page/>` would keep getting updates:

```js
function Freezer() {
  const snapshot = useRef()
  const freeze = useRef()
  const isLoading = useSelector(state => state.loadingIndicator.isLoadingRoute)
  useEffect(() => {
    if (isLoadingRoute) {
      freeze.current = true
    }
  }, [isLoading])
  if (freeze.current) {
    return snapshot.current
  }
  return snapshot.current = <Page/>
}
```

It could work if there was a way in React to somehow snapshot the whole tree with components like `<Page/>` being reduced to simple `<div/>`s and such.
I still can implement some hack like:

```js
function Page() {
  return window.latestPageRenderResult = renderPage()
}
```

And then use `window.latestPageRenderResult` in the `<Freezer/>`.

Maybe I'll have some other ideas...

**Comment by taion** [comment]
yeah, makes sense. i think something like the static container approach we have right now is the best possible without suspense, but it doesn't fully work with redux.

suspense makes all of this much easier. some day...
