### ISSUE TITLE
Documentation: Router comparison

### ISSUE THREAD

**Issue by Shannanigans** [4Catalyzer/found#709]
It would be very useful to be able to view a succinct router feature comparison in order to quickly inform prospective adopters of the pros and cons of using this router library vs the other available options.

**Comment by taion** [comment]
I'm going to consolidate this with https://github.com/4Catalyzer/found/issues/180 to keep things organized. It's a good idea, but I haven't had the chance to get around to it.

Feel free to follow up in that thread with any specific questions you might have, and I'll do my best to answer.

**Comment by Shannanigans** [comment]
@taion the router challenge sounds like a great idea, but listing some core differences in features and approach between react-router and found in a table in the readme would go a long way. This communicates differences without having to read the react challenge example code, which might not even illustrate differences.
