### ISSUE TITLE
Can I have independent routes for page and side panel components at the same time?

### ISSUE THREAD

**Issue by hexwit** [4Catalyzer/found#719]
I have integrated 'found' router in my application, and it works fine while I am navigating menu for main pages content. 
Now I have a side panel, that I want to integrate into routing. 
And manage main content route and side panel content route independently. 

So the goal is to have some component rendered in main page, and some other component rendered in side panel at the same time. And route should represent this state. So I can reload my page, and the same components are rendered. 

Is it possible with found? If yes, could you give an example?

**Comment by taion** [comment]
Yes, see https://github.com/4Catalyzer/found#named-child-routes
