### ISSUE TITLE
Hot reloading with custom redux store

### ISSUE THREAD

**Issue by aoc** [4Catalyzer/found#72]
Hi, I'm having a hard time trying to make webpack + react hot reloading when using this router.

My current setup:
* server side rendering
* already using redux, so I followed the instructions from **Server-side rendering with custom Redux store** section
* react-hot-loader v3

Hot reloading is working until I try to use the router. I think it's related to the routes being defined in the redux store middleware -> createMatchEnhancer -> matcher.

Could you please provide some guidelines or an example on how to achieve this?

thanks!

**Comment by steida** [comment]
Check https://github.com/este/este/tree/react-navigation (wrong branch name, nevermind).
I solved it. The thing is, you have to use vanilla hot reloading, it means, no react-hot-loader. It basically rerenders the whole app on any change, so the local state is gone, but Redux state remains. This is the best approach. It just works.

**Comment by taion** [comment]
As it stands, a route change is essentially a middleware change, so you'll need to replace the store entirely (v. if you just changed the reducers).

If you do recycle the store, you will need to then re-render the entire app. Make sure you dispatch `FarceActions.init()` when you do so.

**Comment by aoc** [comment]
Thanks @steida @taion ! I'll try your suggestions

**Comment by steida** [comment]
Full example of Found router with SSR and hot reloading: https://github.com/este/este

**Comment by taion** [comment]
@steida What ends up happening when you hot reload? Do you end up re-rendering the entire page?

**Comment by steida** [comment]
@taion Re-rendering the entire page is the only reliable hot reloading. Even Dan Abramov gave up all edge cases. When the app state is stored in Redux, re-rending the entire page is ok. With such setup, we can have hot reloadable actions, reducers, components wrapped in higher order components, it just works. That's what I had to do: 

https://github.com/este/este/blob/master/src/browser/app/Root.js#L33

On any component change, get fresh Root with fresh routeConfig.

**Comment by steida** [comment]
@aoc I think you can close this issue. It's demonstrated in Este.

**Comment by taion** [comment]
I'm adding first-class support for reloading route configs in https://github.com/4Catalyzer/found/pull/152.
