### ISSUE TITLE
Is there any way to redirect in component like in react-router?

### ISSUE THREAD

**Issue by MarcStdt** [4Catalyzer/found#757]
In react-router you can simply use <Redirect /> to redirect in a component (not a route) to another route.
<Redirect /> seems to work fairly different in found.

e.g. for react-router:
``` javascript
if (redirect) {
 return <Redirect to="/example" />
}

return (
 <Main>...</Main>);
```

Is such a thing also possible with found? I din't find any solution yet, but I am new to this library.
If there is no solution. Whats the best way to accomplish a similar behaviour?

**Comment by taion** [comment]
The best way to do this is to call `router.replace` in a `useEffect` hook, or something to that effect: https://github.com/4Catalyzer/found#programmatic-navigation

A redirect isn't _really_ something that's renderable in any case - it's just an after-render effect/action that you do with the router.

**Comment by MarcStdt** [comment]
Thank you!
