### ISSUE TITLE
How to bypass initial getData?

### ISSUE THREAD

**Issue by steida** [4Catalyzer/found#76]
If we getData on the server side and deliver them to the client withing Redux initialState, how we can bypass the initial getData? Manual checking?

**Comment by taion** [comment]
You dehydrate and rehydrate the store as normally; the idea would be that `getData` on client then just hits the cache. See https://github.com/4Catalyzer/found/tree/master/examples/universal-redux

**Comment by eligolding** [comment]
Is there a way to accomplish this when the data being fetched is not being stored in redux, rather just being returned as a prop to the component?

**Comment by taion** [comment]
You need to provide the data to the client to be hydrated in some manner. It doesn't have to be Redux, but the logic does need to be handled in `getData`. Found can't handle this in general because there's no guarantee that the return value of `getData` is serializable.
