### ISSUE TITLE
What I do wrong with example?

### ISSUE THREAD

**Issue by AngryBotIY** [4Catalyzer/found#796]
Here is basic usage of found package: https://codesandbox.io/s/found-mn6sw

It doesn't work as expected, can someone help to explain what happened?

When app is started here is 404.

**Comment by taion** [comment]
You need to add an empty "route" to make `/` match, like

```
    <Route path="/" Component={App}>
      <Route />
      <Route
```

See also https://github.com/4Catalyzer/found/issues/657.
