### ISSUE TITLE
How to change root route to be something other than /

### ISSUE THREAD

**Issue by grimunit** [4Catalyzer/found#82]
Hey I've been researching and trying different things but can't seem to figure out how I could change the root route to be something like `/app` instead of just `/`. Would I just wrap everything in a `<Redirect>` component? 

The use case is basically having a new SPA built along side an existing application and we want to have it nested inside the `/app` directory and so would like to treat that as the "root" for the SPA.

**Comment by grimunit** [comment]
Hmm well for now I'll just be prepending `/app` to all of my links, for example:

`<Link to="/app/users" />`

**Comment by grimunit** [comment]
And in my routeConfig I just have the path pointing to `/app` like so:

`<Route path="/app" Component={App}>`

**Comment by taion** [comment]
Use `createFarceRouter`, and use https://github.com/4Catalyzer/farce#createbasenamemiddleware.

**Comment by grimunit** [comment]
Awesome this works great, thanks @taion

**Comment by grimunit** [comment]
And holy crap if anyone comes across this and is having trouble with apache rewrite rules. Everyone recommends that you basically route all the traffic from the root like so: 

`RewriteRule (.*) index.html [QSA,L]`

However if you're unfamiliar with how `.htaccess` files work like I was, then it will take you forever to figure out you need to create another `.htaccess` file and put it inside the subdirectory where your SPA will be, so for me I'm going to have it inside the `/app` subdirectory.

**Comment by thomasparsons** [comment]
Is there an example of this being applied to the Router/createFarceRouter?

**Comment by taion** [comment]
You just pass it in w/`historyMiddlewares` on the config object

**Comment by thomasparsons** [comment]
like this: 
```
const Router = createFarceRouter({
  basenameMiddleware,
  historyMiddlewares: [queryMiddleware],
  ...
});
```

or like this:
```
const Router = createFarceRouter({
  historyMiddlewares: [queryMiddleware, basenameMiddleware],
  ...
});
```

where `basenameMiddleware` is `createBasenameMiddleware({ basename: '/world' });`

**Comment by taion** [comment]
Either... depends whether you want the query handling or not

**Comment by thomasparsons** [comment]
thanks, I got it working with this: `historyMiddlewares: [queryMiddleware, basenameMiddleware],` 

don't know why it wasnt working before, odd! 

thanks
