### ISSUE TITLE
How to get initial state of found for testing

### ISSUE THREAD

**Issue by grimunit** [4Catalyzer/found#91]
How would you recommend I create an instance of founds initial state so I can test against a mocked version of the redux found reducer state?

**Comment by taion** [comment]
I'm not sure what you mean. Can you elaborate?

If you need to get the routing state from the reducer, just dispatch the action and see what's in the store.

Otherwise the server rendering API should give you what you want.

**Comment by taion** [comment]
Use the server rendering API.
