### ISSUE TITLE
Changelog / Migration Guide

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#964]
Hi.
I don't see any CHANGELOG or Migration Guide anywhere.
In GitHub releases, the last one is `v0.5.9` which is clearly outdated.
I can see that after `0.6.0` there have been 1.0 and 1.1.
Why is there no CHANGELOG? That's an established practice to have one in a library's repo.

**Comment by jquense** [comment]
The changelog is the commit history. We bumped the version to v1 just to reflect the state of the project there shouldn't be any breaking changes
