### ISSUE TITLE
Migrate to React 18

### ISSUE THREAD

**Issue by catamphetamine** [4Catalyzer/found#965]
The current version of this library doesn't support React 18 because using React 18 requires using `react-redux@8` and this library uses `react-redux@7`.

**Comment by catamphetamine** [comment]
In case you wondered, it's backwards-compatible, so non-breaking.
https://github.com/reduxjs/react-redux/releases

> React-Redux now requires the new useSyncExternalStore API in React 18. By default, it uses the "shim" package which backfills that API in earlier React versions, so React-Redux v8 is compatible with all React versions that have hooks (16.8+, and React Native 0.59+) as its acceptable peer dependencies.

**Comment by golota60** [comment]
This has been resolved in [this commit](https://github.com/4Catalyzer/found/commit/c7d03018f422c839b69d04f209f16ef341916ecb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)  :tada:
