### ISSUE TITLE
getData - fetch throwing after hot reload

### ISSUE THREAD

**Issue by mirimCZ** [4Catalyzer/found#99]
Hi,

the situation is, that I need to use fetch (or similar) to get JSON data from api in getData method on <Route> component. When I enter the page (or after hard refresh), everything works as expected, all actions are fired properly, store is updated.

But I encounter problems once I change something in my code and my HMR starts to replace modules. First of all, you can notice that the action is being triggered twice, that does not seems correct. This behaviour also appears in este, which my stack is heavily based upon (thx Daniel if u r reading this :) ).

In contradiction to este, I'm not using firebase, and where "queryFirebase.js" sits I'm simply calling action I choose. Error I'm getting is "net::ERR_CONNECTION_REFUSED", when I inspect headers of the request it's basically empty, there is no method, no status code, seems like the request is getting canceled or something. Also there is redux-promise-middleware in the middle.

```
<Route
  Component={MyPage}
  getData={pageRequest(getServerData)}
/>

const pageRequest = (action) => (
  ({ context: { store } }) => store.dispatch(({ ...deps }) => action(deps))
)

const getServerData = ({ fetch }): Action => ({
  type: 'GET_DATA',
  payload: fetch('http://localhost:3000/api/v1/data')
    .then(response => response.json())
    .catch(e => console.log('Fetching failed', e)),
})
```

I'm rather lost, thanks for any help. If you need more info I will provide as much as I can.

**Comment by taion** [comment]
If you're doing HMR, you need to re-render the router. Probably something is happening where whatever is setting up that `fetch` function you are using is not running before `getData` gets called again.

**Comment by taion** [comment]
I'm honestly not sure. It looks like you're depending on some additional setup to configure the `fetch` you pass in there to populate headers, method, &c., so perhaps just set a breakpoint and make sure that your `fetch` function is configured correctly and is what you expect.

**Comment by taion** [comment]
Let's follow up on https://github.com/4Catalyzer/found/issues/104.

**Comment by mirimCZ** [comment]
Well... fetch throwing is indeed caused by something I did. IDK where yet, but I tried to do same thing in este and it works there just fine. I will get back if I figure out where the problem was, maybe it will help others :)

But still - getData() is being called twice, even there.

**Comment by taion** [comment]
`getData` getting called twice is probably #104 – we ought to have a way to reload routes without re-creating the store. Probably on the hot reload you're both replacing reducers and recreating the store or something, causing two routing updates?

**Comment by mirimCZ** [comment]
Don't know TBH, but that sounds bit unlikely, but depends when exactly is the getData fired, AFAIK it should be at component will mount? You can see the HMR replacement [here](https://github.com/este/este/blob/master/src/browser/main.js) I'm using same approach.

About fetch problem: so far I figured, that it works fine when I'm requesting Marwel gateway API (https://gateway.marvel.com:443), but as soon as I switched to localhost the errors were back. Looks like it's server related. "Hooray". I'm playing around on [este fork](https://github.com/mirimCZ/este/blob/heroes/src/browser/app/routeConfig.js), just about to push not working example...

**Comment by taion** [comment]
cc @steida I think that's not quite the right way to do hot reloading, which is why I want to bring that hot reloading logic into this repo – I think we just need to re-run the existing match with the new routes, rather than re-rendering.
